queries = "queries/"
destination = "clorinde"
async = true
sync = false

[types]
derive-traits = ["serde::Serialize", "serde::Deserialize"]

[manifest.package]
name = "qontinui-db"
version = "0.1.0"
edition = "2021"
