// AUTO-GENERATED by generate-spec-registry.ts — DO NOT EDIT
//
// 92 spec files discovered (14 web + 78 runner).
//
// Regenerate: cd ../qontinui-web/frontend && npx tsx scripts/generate-spec-registry.ts

import type { DiscoveredSpec } from "./spec-prompt-builder";

import activeRunsSpec from "../../../qontinui-web/frontend/src/app/(app)/runs/active/active-runs.spec.uibridge.json";
import aiSettingsSpec from "../../../qontinui-web/frontend/src/app/(app)/settings/ai/ai-settings.spec.uibridge.json";
import chatSpec from "../../../qontinui-web/frontend/src/app/(app)/chat/chat.spec.uibridge.json";
import contextsSpec from "../../../qontinui-web/frontend/src/app/(app)/build/contexts/contexts.spec.uibridge.json";
import errorMonitorSpec from "../../../qontinui-web/frontend/src/app/(app)/tools/error-monitor/error-monitor.spec.uibridge.json";
import executeSpec from "../../../qontinui-web/frontend/src/app/(app)/execute/execute.spec.uibridge.json";
import findingsSpec from "../../../qontinui-web/frontend/src/app/(app)/runs/findings/findings.spec.uibridge.json";
import inspectorSpec from "../../../qontinui-web/frontend/src/app/(app)/tools/inspector/inspector.spec.uibridge.json";
import runnersSpec from "../../../qontinui-web/frontend/src/app/(app)/runners/runners.spec.uibridge.json";
import runsSpec from "../../../qontinui-web/frontend/src/app/(app)/runs/runs.spec.uibridge.json";
import statisticsSpec from "../../../qontinui-web/frontend/src/app/(app)/runs/statistics/statistics.spec.uibridge.json";
import templatesSpec from "../../../qontinui-web/frontend/src/app/(app)/build/templates/templates.spec.uibridge.json";
import uiBridgeStatesSpec from "../../../qontinui-web/frontend/src/app/(app)/automation-builder/ui-bridge-states/ui-bridge-states.spec.uibridge.json";
import workflowsSpec from "../../../qontinui-web/frontend/src/app/(app)/build/workflows/workflows.spec.uibridge.json";
import runnerAccessibilityExplorerSpec from "../specs/accessibility-explorer.spec.uibridge.json";
import runnerArchitectureSpec from "../specs/architecture.spec.uibridge.json";
import runnerActionPlanSpec from "../specs/action-plan.spec.uibridge.json";
import runnerActiveSpec from "../specs/active.spec.uibridge.json";
import runnerActivityTimelineSpec from "../specs/activity-timeline.spec.uibridge.json";
import runnerAdaptiveLearningSpec from "../specs/adaptive-learning.spec.uibridge.json";
import runnerAutomationHealthSpec from "../specs/automation-health.spec.uibridge.json";
import runnerBlameAttributionSpec from "../specs/blame-attribution.spec.uibridge.json";
import runnerCaptureSpec from "../specs/capture.spec.uibridge.json";
import runnerCheckBuilderSpec from "../specs/check-builder.spec.uibridge.json";
import runnerCheckGroupBuilderSpec from "../specs/check-group-builder.spec.uibridge.json";
import runnerConfigFindingsSpec from "../specs/config-findings.spec.uibridge.json";
import runnerConfigHooksSpec from "../specs/config-hooks.spec.uibridge.json";
import runnerConfigUiBridgeSpec from "../specs/config-ui-bridge.spec.uibridge.json";
import runnerContextBuilderSpec from "../specs/context-builder.spec.uibridge.json";
import runnerConvergenceWidgetSpec from "../specs/convergence-widget.spec.uibridge.json";
import runnerCostControlSpec from "../specs/cost-control.spec.uibridge.json";
import runnerCrossRunAnalyticsSpec from "../specs/cross-run-analytics.spec.uibridge.json";
import runnerDagWorkflowEditorSpec from "../specs/dag-workflow-editor.spec.uibridge.json";
import runnerDebugSpec from "../specs/debug.spec.uibridge.json";
import runnerElementReliabilitySpec from "../specs/element-reliability.spec.uibridge.json";
import runnerErrorMonitorSpec from "../specs/error-monitor.spec.uibridge.json";
import runnerEvaluationSpec from "../specs/evaluation.spec.uibridge.json";
import runnerEventHistorySpec from "../specs/event-history.spec.uibridge.json";
import runnerExecuteSpec from "../specs/execute.spec.uibridge.json";
import runnerFlowControlSpec from "../specs/flow-control.spec.uibridge.json";
import runnerGeneratorEvalSpec from "../specs/generator-eval.spec.uibridge.json";
import runnerGraphInsightsSpec from "../specs/graph-insights.spec.uibridge.json";
import runnerGraphqlDashboardIntegrationSpec from "../specs/graphql-dashboard-integration.spec.uibridge.json";
import runnerGraphqlInfrastructureSpec from "../specs/graphql-infrastructure.spec.uibridge.json";
import runnerGraphqlLiveTaskSpec from "../specs/graphql-live-task.spec.uibridge.json";
import runnerGuiAutomationSpec from "../specs/gui-automation.spec.uibridge.json";
import runnerHelpSpec from "../specs/help.spec.uibridge.json";
import runnerKnowledgeAcquisitionSpec from "../specs/knowledge-acquisition.spec.uibridge.json";
import runnerKnowledgeExplorerSpec from "../specs/knowledge-explorer.spec.uibridge.json";
import runnerLibrarySpec from "../specs/library.spec.uibridge.json";
import runnerLlmAnalyticsUiBridgeSpec from "../specs/llm-analytics-ui-bridge.spec.uibridge.json";
import runnerLlmObservabilitySpec from "../specs/llm-observability.spec.uibridge.json";
import runnerMetaOptimizerPageSpec from "../specs/meta-optimizer-page.spec.uibridge.json";
import runnerOnlineLearningSpec from "../specs/online-learning.spec.uibridge.json";
import runnerOpikIntegrationSpec from "../specs/opik-integration.spec.uibridge.json";
import runnerOrchestrationLoopSpec from "../specs/orchestration-loop.spec.uibridge.json";
import runnerPipelineEventsSpec from "../specs/pipeline-events.spec.uibridge.json";
import runnerPlaywrightTestBuilderSpec from "../specs/playwright-test-builder.spec.uibridge.json";
import runnerProcessesSpec from "../specs/processes.spec.uibridge.json";
import runnerPromptHomeSpec from "../specs/prompt-home.spec.uibridge.json";
import runnerPromptManagementSpec from "../specs/prompt-management.spec.uibridge.json";
import runnerReflectionSpec from "../specs/reflection.spec.uibridge.json";
import runnerRuleInfluenceSpec from "../specs/rule-influence.spec.uibridge.json";
import runnerRunActionsSpec from "../specs/run-actions.spec.uibridge.json";
import runnerRunAiDataSpec from "../specs/run-ai-data.spec.uibridge.json";
import runnerRunAiOutputSpec from "../specs/run-ai-output.spec.uibridge.json";
import runnerRunFeedbackCostsSpec from "../specs/run-feedback-costs.spec.uibridge.json";
import runnerRunFindingsSpec from "../specs/run-findings.spec.uibridge.json";
import runnerRunImageRecognitionSpec from "../specs/run-image-recognition.spec.uibridge.json";
import runnerRunStateExplorerSpec from "../specs/run-state-explorer.spec.uibridge.json";
import runnerRunStatisticsSpec from "../specs/run-statistics.spec.uibridge.json";
import runnerRunSummarySpec from "../specs/run-summary.spec.uibridge.json";
import runnerRunTestsSpec from "../specs/run-tests.spec.uibridge.json";
import runnerRunTracesSpec from "../specs/run-traces.spec.uibridge.json";
import runnerScheduledTasksSpec from "../specs/scheduled-tasks.spec.uibridge.json";
import runnerSecuritySettingsSpec from "../specs/security-settings.spec.uibridge.json";
import runnerSettingsBackupSpec from "../specs/settings-backup.spec.uibridge.json";
import runnerSettingsSpec from "../specs/settings.spec.uibridge.json";
import runnerShellCommandBuilderSpec from "../specs/shell-command-builder.spec.uibridge.json";
import runnerSidebarSpec from "../specs/sidebar.spec.uibridge.json";
import runnerSkillsSpec from "../specs/skills.spec.uibridge.json";
import runnerSpecsSpec from "../specs/specs.spec.uibridge.json";
import runnerSpecsPageMixedSpec from "../specs/specs-page-mixed.spec.uibridge.json";
import runnerSpecsPageSpec from "../specs/specs-page.spec.uibridge.json";
import runnerStateMachineSpec from "../specs/state-machine.spec.uibridge.json";
import runnerStepBuildersSpec from "../specs/step-builders.spec.uibridge.json";
import runnerTaskBuilderSpec from "../specs/task-builder.spec.uibridge.json";
import runnerTerminalSpec from "../specs/terminal.spec.uibridge.json";
import runnerTriggersSpec from "../specs/triggers.spec.uibridge.json";
import runnerTurixCuaMultimodalSpec from "../specs/turix-cua-multimodal.spec.uibridge.json";
import runnerUnifiedSearchSpec from "../specs/unified-search.spec.uibridge.json";
import runnerVgaSpec from "../specs/vga.spec.uibridge.json";
import runnerVisualDashboardSpec from "../specs/visual-dashboard.spec.uibridge.json";
import runnerWatchersSpec from "../specs/watchers.spec.uibridge.json";
import runnerWrappersSpec from "../specs/wrappers.spec.uibridge.json";
import runnerWorkflowCriteriaSpec from "../specs/workflow-criteria.spec.uibridge.json";
import runnerWorkflowVersionsSpec from "../specs/workflow-versions.spec.uibridge.json";
import runnerWorkflowsSpec from "../specs/workflows.spec.uibridge.json";

interface RawSpec {
  specId: string;
  appName: "Qontinui Web" | "Qontinui Runner";
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  json: any;
}

const ALL_SPECS: RawSpec[] = [
  { specId: "active-runs", appName: "Qontinui Web", json: activeRunsSpec },
  { specId: "ai-settings", appName: "Qontinui Web", json: aiSettingsSpec },
  { specId: "chat", appName: "Qontinui Web", json: chatSpec },
  { specId: "contexts", appName: "Qontinui Web", json: contextsSpec },
  { specId: "error-monitor", appName: "Qontinui Web", json: errorMonitorSpec },
  { specId: "execute", appName: "Qontinui Web", json: executeSpec },
  { specId: "findings", appName: "Qontinui Web", json: findingsSpec },
  { specId: "inspector", appName: "Qontinui Web", json: inspectorSpec },
  { specId: "runners", appName: "Qontinui Web", json: runnersSpec },
  { specId: "runs", appName: "Qontinui Web", json: runsSpec },
  { specId: "statistics", appName: "Qontinui Web", json: statisticsSpec },
  { specId: "templates", appName: "Qontinui Web", json: templatesSpec },
  { specId: "ui-bridge-states", appName: "Qontinui Web", json: uiBridgeStatesSpec },
  { specId: "workflows", appName: "Qontinui Web", json: workflowsSpec },
  { specId: "runner:architecture", appName: "Qontinui Runner", json: runnerArchitectureSpec },
  {
    specId: "runner:accessibility-explorer",
    appName: "Qontinui Runner",
    json: runnerAccessibilityExplorerSpec,
  },
  { specId: "runner:action-plan", appName: "Qontinui Runner", json: runnerActionPlanSpec },
  { specId: "runner:active", appName: "Qontinui Runner", json: runnerActiveSpec },
  {
    specId: "runner:activity-timeline",
    appName: "Qontinui Runner",
    json: runnerActivityTimelineSpec,
  },
  {
    specId: "runner:adaptive-learning",
    appName: "Qontinui Runner",
    json: runnerAdaptiveLearningSpec,
  },
  {
    specId: "runner:automation-health",
    appName: "Qontinui Runner",
    json: runnerAutomationHealthSpec,
  },
  {
    specId: "runner:blame-attribution",
    appName: "Qontinui Runner",
    json: runnerBlameAttributionSpec,
  },
  { specId: "runner:capture", appName: "Qontinui Runner", json: runnerCaptureSpec },
  { specId: "runner:check-builder", appName: "Qontinui Runner", json: runnerCheckBuilderSpec },
  {
    specId: "runner:check-group-builder",
    appName: "Qontinui Runner",
    json: runnerCheckGroupBuilderSpec,
  },
  { specId: "runner:config-findings", appName: "Qontinui Runner", json: runnerConfigFindingsSpec },
  { specId: "runner:config-hooks", appName: "Qontinui Runner", json: runnerConfigHooksSpec },
  { specId: "runner:config-ui-bridge", appName: "Qontinui Runner", json: runnerConfigUiBridgeSpec },
  { specId: "runner:context-builder", appName: "Qontinui Runner", json: runnerContextBuilderSpec },
  {
    specId: "runner:convergence-widget",
    appName: "Qontinui Runner",
    json: runnerConvergenceWidgetSpec,
  },
  { specId: "runner:cost-control", appName: "Qontinui Runner", json: runnerCostControlSpec },
  {
    specId: "runner:cross-run-analytics",
    appName: "Qontinui Runner",
    json: runnerCrossRunAnalyticsSpec,
  },
  {
    specId: "runner:dag-workflow-editor",
    appName: "Qontinui Runner",
    json: runnerDagWorkflowEditorSpec,
  },
  { specId: "runner:debug", appName: "Qontinui Runner", json: runnerDebugSpec },
  {
    specId: "runner:element-reliability",
    appName: "Qontinui Runner",
    json: runnerElementReliabilitySpec,
  },
  { specId: "runner:error-monitor", appName: "Qontinui Runner", json: runnerErrorMonitorSpec },
  { specId: "runner:evaluation", appName: "Qontinui Runner", json: runnerEvaluationSpec },
  { specId: "runner:event-history", appName: "Qontinui Runner", json: runnerEventHistorySpec },
  { specId: "runner:execute", appName: "Qontinui Runner", json: runnerExecuteSpec },
  { specId: "runner:flow-control", appName: "Qontinui Runner", json: runnerFlowControlSpec },
  { specId: "runner:generator-eval", appName: "Qontinui Runner", json: runnerGeneratorEvalSpec },
  { specId: "runner:graph-insights", appName: "Qontinui Runner", json: runnerGraphInsightsSpec },
  {
    specId: "runner:graphql-dashboard-integration",
    appName: "Qontinui Runner",
    json: runnerGraphqlDashboardIntegrationSpec,
  },
  {
    specId: "runner:graphql-infrastructure",
    appName: "Qontinui Runner",
    json: runnerGraphqlInfrastructureSpec,
  },
  {
    specId: "runner:graphql-live-task",
    appName: "Qontinui Runner",
    json: runnerGraphqlLiveTaskSpec,
  },
  { specId: "runner:gui-automation", appName: "Qontinui Runner", json: runnerGuiAutomationSpec },
  { specId: "runner:help", appName: "Qontinui Runner", json: runnerHelpSpec },
  {
    specId: "runner:knowledge-acquisition",
    appName: "Qontinui Runner",
    json: runnerKnowledgeAcquisitionSpec,
  },
  {
    specId: "runner:knowledge-explorer",
    appName: "Qontinui Runner",
    json: runnerKnowledgeExplorerSpec,
  },
  { specId: "runner:library", appName: "Qontinui Runner", json: runnerLibrarySpec },
  {
    specId: "runner:llm-analytics-ui-bridge",
    appName: "Qontinui Runner",
    json: runnerLlmAnalyticsUiBridgeSpec,
  },
  {
    specId: "runner:llm-observability",
    appName: "Qontinui Runner",
    json: runnerLlmObservabilitySpec,
  },
  {
    specId: "runner:meta-optimizer-page",
    appName: "Qontinui Runner",
    json: runnerMetaOptimizerPageSpec,
  },
  { specId: "runner:online-learning", appName: "Qontinui Runner", json: runnerOnlineLearningSpec },
  {
    specId: "runner:opik-integration",
    appName: "Qontinui Runner",
    json: runnerOpikIntegrationSpec,
  },
  {
    specId: "runner:orchestration-loop",
    appName: "Qontinui Runner",
    json: runnerOrchestrationLoopSpec,
  },
  { specId: "runner:pipeline-events", appName: "Qontinui Runner", json: runnerPipelineEventsSpec },
  {
    specId: "runner:playwright-test-builder",
    appName: "Qontinui Runner",
    json: runnerPlaywrightTestBuilderSpec,
  },
  { specId: "runner:processes", appName: "Qontinui Runner", json: runnerProcessesSpec },
  { specId: "runner:prompt-home", appName: "Qontinui Runner", json: runnerPromptHomeSpec },
  {
    specId: "runner:prompt-management",
    appName: "Qontinui Runner",
    json: runnerPromptManagementSpec,
  },
  { specId: "runner:reflection", appName: "Qontinui Runner", json: runnerReflectionSpec },
  { specId: "runner:rule-influence", appName: "Qontinui Runner", json: runnerRuleInfluenceSpec },
  { specId: "runner:run-actions", appName: "Qontinui Runner", json: runnerRunActionsSpec },
  { specId: "runner:run-ai-data", appName: "Qontinui Runner", json: runnerRunAiDataSpec },
  { specId: "runner:run-ai-output", appName: "Qontinui Runner", json: runnerRunAiOutputSpec },
  {
    specId: "runner:run-feedback-costs",
    appName: "Qontinui Runner",
    json: runnerRunFeedbackCostsSpec,
  },
  { specId: "runner:run-findings", appName: "Qontinui Runner", json: runnerRunFindingsSpec },
  {
    specId: "runner:run-image-recognition",
    appName: "Qontinui Runner",
    json: runnerRunImageRecognitionSpec,
  },
  {
    specId: "runner:run-state-explorer",
    appName: "Qontinui Runner",
    json: runnerRunStateExplorerSpec,
  },
  { specId: "runner:run-statistics", appName: "Qontinui Runner", json: runnerRunStatisticsSpec },
  { specId: "runner:run-summary", appName: "Qontinui Runner", json: runnerRunSummarySpec },
  { specId: "runner:run-tests", appName: "Qontinui Runner", json: runnerRunTestsSpec },
  { specId: "runner:run-traces", appName: "Qontinui Runner", json: runnerRunTracesSpec },
  { specId: "runner:scheduled-tasks", appName: "Qontinui Runner", json: runnerScheduledTasksSpec },
  {
    specId: "runner:security-settings",
    appName: "Qontinui Runner",
    json: runnerSecuritySettingsSpec,
  },
  {
    specId: "runner:settings-backup",
    appName: "Qontinui Runner",
    json: runnerSettingsBackupSpec,
  },
  { specId: "runner:settings", appName: "Qontinui Runner", json: runnerSettingsSpec },
  {
    specId: "runner:shell-command-builder",
    appName: "Qontinui Runner",
    json: runnerShellCommandBuilderSpec,
  },
  { specId: "runner:sidebar", appName: "Qontinui Runner", json: runnerSidebarSpec },
  { specId: "runner:skills", appName: "Qontinui Runner", json: runnerSkillsSpec },
  { specId: "runner:specs", appName: "Qontinui Runner", json: runnerSpecsSpec },
  { specId: "runner:specs-page-mixed", appName: "Qontinui Runner", json: runnerSpecsPageMixedSpec },
  { specId: "runner:specs-page", appName: "Qontinui Runner", json: runnerSpecsPageSpec },
  { specId: "runner:state-machine", appName: "Qontinui Runner", json: runnerStateMachineSpec },
  { specId: "runner:step-builders", appName: "Qontinui Runner", json: runnerStepBuildersSpec },
  { specId: "runner:task-builder", appName: "Qontinui Runner", json: runnerTaskBuilderSpec },
  { specId: "runner:terminal", appName: "Qontinui Runner", json: runnerTerminalSpec },
  { specId: "runner:triggers", appName: "Qontinui Runner", json: runnerTriggersSpec },
  {
    specId: "runner:turix-cua-multimodal",
    appName: "Qontinui Runner",
    json: runnerTurixCuaMultimodalSpec,
  },
  { specId: "runner:unified-search", appName: "Qontinui Runner", json: runnerUnifiedSearchSpec },
  { specId: "runner:vga", appName: "Qontinui Runner", json: runnerVgaSpec },
  {
    specId: "runner:visual-dashboard",
    appName: "Qontinui Runner",
    json: runnerVisualDashboardSpec,
  },
  { specId: "runner:watchers", appName: "Qontinui Runner", json: runnerWatchersSpec },
  { specId: "runner:wrappers", appName: "Qontinui Runner", json: runnerWrappersSpec },
  {
    specId: "runner:workflow-criteria",
    appName: "Qontinui Runner",
    json: runnerWorkflowCriteriaSpec,
  },
  {
    specId: "runner:workflow-versions",
    appName: "Qontinui Runner",
    json: runnerWorkflowVersionsSpec,
  },
  { specId: "runner:workflows", appName: "Qontinui Runner", json: runnerWorkflowsSpec },
];

/**
 * Get all page specs as DiscoveredSpec[].
 * Returns all groups from all spec files — no category filtering.
 */
export function getAllSpecs(): DiscoveredSpec[] {
  const result: DiscoveredSpec[] = [];

  for (const { specId, appName, json } of ALL_SPECS) {
    const groups = json.groups ?? [];
    if (groups.length === 0) continue;

    result.push({
      specId,
      appName,
      config: {
        version: json.version ?? "1.0.0",
        description: json.description ?? "",
        groups,
        metadata: json.metadata,
        stateMachine: json.stateMachine,
      },
    });
  }

  return result;
}

export function getKnownPages(): { expectedSpecId: string; label: string; pageUrl: string }[] {
  return getAllSpecs()
    .filter((s) => s.config.metadata?.pageUrl)
    .map((s) => ({
      expectedSpecId: s.specId,
      label: (s.config.metadata?.component as string) || s.specId,
      pageUrl: s.config.metadata?.pageUrl as string,
    }));
}
