// AUTO-GENERATED by generate-spec-registry.ts — DO NOT EDIT
//
// 51 spec files discovered (14 web + 37 runner).
//
// Regenerate: cd ../qontinui-web/frontend && npx tsx scripts/generate-spec-registry.ts

import type { DiscoveredSpec } from "./spec-prompt-builder";

import activeRunsSpec from "../../../qontinui-web/frontend/src/app/(app)/runs/active/active-runs.spec.uibridge.json";
import aiSettingsSpec from "../../../qontinui-web/frontend/src/app/(app)/settings/ai/ai-settings.spec.uibridge.json";
import chatSpec from "../../../qontinui-web/frontend/src/app/(app)/chat/chat.spec.uibridge.json";
import contextsSpec from "../../../qontinui-web/frontend/src/app/(app)/build/contexts/contexts.spec.uibridge.json";
import errorMonitorSpec from "../../../qontinui-web/frontend/src/app/(app)/tools/error-monitor/error-monitor.spec.uibridge.json";
import executeSpec from "../../../qontinui-web/frontend/src/app/(app)/execute/execute.spec.uibridge.json";
import findingsSpec from "../../../qontinui-web/frontend/src/app/(app)/runs/findings/findings.spec.uibridge.json";
import inspectorSpec from "../../../qontinui-web/frontend/src/app/(app)/tools/inspector/inspector.spec.uibridge.json";
import runnersSpec from "../../../qontinui-web/frontend/src/app/(app)/runners/runners.spec.uibridge.json";
import runsSpec from "../../../qontinui-web/frontend/src/app/(app)/runs/runs.spec.uibridge.json";
import statisticsSpec from "../../../qontinui-web/frontend/src/app/(app)/runs/statistics/statistics.spec.uibridge.json";
import templatesSpec from "../../../qontinui-web/frontend/src/app/(app)/build/templates/templates.spec.uibridge.json";
import uiBridgeStatesSpec from "../../../qontinui-web/frontend/src/app/(app)/automation-builder/ui-bridge-states/ui-bridge-states.spec.uibridge.json";
import workflowsSpec from "../../../qontinui-web/frontend/src/app/(app)/build/workflows/workflows.spec.uibridge.json";
import runnerActiveSpec from "../specs/active.spec.uibridge.json";
import runnerCaptureSpec from "../specs/capture.spec.uibridge.json";
import runnerCheckBuilderSpec from "../specs/check-builder.spec.uibridge.json";
import runnerCheckGroupBuilderSpec from "../specs/check-group-builder.spec.uibridge.json";
import runnerConfigFindingsSpec from "../specs/config-findings.spec.uibridge.json";
import runnerConfigHooksSpec from "../specs/config-hooks.spec.uibridge.json";
import runnerConfigUiBridgeSpec from "../specs/config-ui-bridge.spec.uibridge.json";
import runnerContextBuilderSpec from "../specs/context-builder.spec.uibridge.json";
import runnerErrorMonitorSpec from "../specs/error-monitor.spec.uibridge.json";
import runnerExecuteSpec from "../specs/execute.spec.uibridge.json";
import runnerGeneratorEvalSpec from "../specs/generator-eval.spec.uibridge.json";
import runnerGuiAutomationSpec from "../specs/gui-automation.spec.uibridge.json";
import runnerHelpSpec from "../specs/help.spec.uibridge.json";
import runnerLibrarySpec from "../specs/library.spec.uibridge.json";
import runnerPlaywrightTestBuilderSpec from "../specs/playwright-test-builder.spec.uibridge.json";
import runnerProcessesSpec from "../specs/processes.spec.uibridge.json";
import runnerReflectionSpec from "../specs/reflection.spec.uibridge.json";
import runnerRunActionsSpec from "../specs/run-actions.spec.uibridge.json";
import runnerRunAiDataSpec from "../specs/run-ai-data.spec.uibridge.json";
import runnerRunAiOutputSpec from "../specs/run-ai-output.spec.uibridge.json";
import runnerRunFindingsSpec from "../specs/run-findings.spec.uibridge.json";
import runnerRunImageRecognitionSpec from "../specs/run-image-recognition.spec.uibridge.json";
import runnerRunStateExplorerSpec from "../specs/run-state-explorer.spec.uibridge.json";
import runnerRunStatisticsSpec from "../specs/run-statistics.spec.uibridge.json";
import runnerRunSummarySpec from "../specs/run-summary.spec.uibridge.json";
import runnerRunTestsSpec from "../specs/run-tests.spec.uibridge.json";
import runnerRunTracesSpec from "../specs/run-traces.spec.uibridge.json";
import runnerScheduledTasksSpec from "../specs/scheduled-tasks.spec.uibridge.json";
import runnerSettingsSpec from "../specs/settings.spec.uibridge.json";
import runnerShellCommandBuilderSpec from "../specs/shell-command-builder.spec.uibridge.json";
import runnerSpecsPageSpec from "../specs/specs-page.spec.uibridge.json";
import runnerSpecsPageMixedSpec from "../specs/specs-page-mixed.spec.uibridge.json";
import runnerStepBuildersSpec from "../specs/step-builders.spec.uibridge.json";
import runnerTaskBuilderSpec from "../specs/task-builder.spec.uibridge.json";
import runnerTerminalSpec from "../specs/terminal.spec.uibridge.json";
import runnerTriggersSpec from "../specs/triggers.spec.uibridge.json";
import runnerWorkflowsSpec from "../specs/workflows.spec.uibridge.json";

interface RawSpec {
  specId: string;
  appName: "Qontinui Web" | "Qontinui Runner";
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  json: any;
}

const ALL_SPECS: RawSpec[] = [
  { specId: "active-runs", appName: "Qontinui Web", json: activeRunsSpec },
  { specId: "ai-settings", appName: "Qontinui Web", json: aiSettingsSpec },
  { specId: "chat", appName: "Qontinui Web", json: chatSpec },
  { specId: "contexts", appName: "Qontinui Web", json: contextsSpec },
  { specId: "error-monitor", appName: "Qontinui Web", json: errorMonitorSpec },
  { specId: "execute", appName: "Qontinui Web", json: executeSpec },
  { specId: "findings", appName: "Qontinui Web", json: findingsSpec },
  { specId: "inspector", appName: "Qontinui Web", json: inspectorSpec },
  { specId: "runners", appName: "Qontinui Web", json: runnersSpec },
  { specId: "runs", appName: "Qontinui Web", json: runsSpec },
  { specId: "statistics", appName: "Qontinui Web", json: statisticsSpec },
  { specId: "templates", appName: "Qontinui Web", json: templatesSpec },
  { specId: "ui-bridge-states", appName: "Qontinui Web", json: uiBridgeStatesSpec },
  { specId: "workflows", appName: "Qontinui Web", json: workflowsSpec },
  { specId: "runner:active", appName: "Qontinui Runner", json: runnerActiveSpec },
  { specId: "runner:capture", appName: "Qontinui Runner", json: runnerCaptureSpec },
  { specId: "runner:check-builder", appName: "Qontinui Runner", json: runnerCheckBuilderSpec },
  {
    specId: "runner:check-group-builder",
    appName: "Qontinui Runner",
    json: runnerCheckGroupBuilderSpec,
  },
  { specId: "runner:config-findings", appName: "Qontinui Runner", json: runnerConfigFindingsSpec },
  { specId: "runner:config-hooks", appName: "Qontinui Runner", json: runnerConfigHooksSpec },
  { specId: "runner:config-ui-bridge", appName: "Qontinui Runner", json: runnerConfigUiBridgeSpec },
  { specId: "runner:context-builder", appName: "Qontinui Runner", json: runnerContextBuilderSpec },
  { specId: "runner:error-monitor", appName: "Qontinui Runner", json: runnerErrorMonitorSpec },
  { specId: "runner:execute", appName: "Qontinui Runner", json: runnerExecuteSpec },
  { specId: "runner:generator-eval", appName: "Qontinui Runner", json: runnerGeneratorEvalSpec },
  { specId: "runner:gui-automation", appName: "Qontinui Runner", json: runnerGuiAutomationSpec },
  { specId: "runner:help", appName: "Qontinui Runner", json: runnerHelpSpec },
  { specId: "runner:library", appName: "Qontinui Runner", json: runnerLibrarySpec },
  {
    specId: "runner:playwright-test-builder",
    appName: "Qontinui Runner",
    json: runnerPlaywrightTestBuilderSpec,
  },
  { specId: "runner:processes", appName: "Qontinui Runner", json: runnerProcessesSpec },
  { specId: "runner:reflection", appName: "Qontinui Runner", json: runnerReflectionSpec },
  { specId: "runner:run-actions", appName: "Qontinui Runner", json: runnerRunActionsSpec },
  { specId: "runner:run-ai-data", appName: "Qontinui Runner", json: runnerRunAiDataSpec },
  { specId: "runner:run-ai-output", appName: "Qontinui Runner", json: runnerRunAiOutputSpec },
  { specId: "runner:run-findings", appName: "Qontinui Runner", json: runnerRunFindingsSpec },
  {
    specId: "runner:run-image-recognition",
    appName: "Qontinui Runner",
    json: runnerRunImageRecognitionSpec,
  },
  {
    specId: "runner:run-state-explorer",
    appName: "Qontinui Runner",
    json: runnerRunStateExplorerSpec,
  },
  { specId: "runner:run-statistics", appName: "Qontinui Runner", json: runnerRunStatisticsSpec },
  { specId: "runner:run-summary", appName: "Qontinui Runner", json: runnerRunSummarySpec },
  { specId: "runner:run-tests", appName: "Qontinui Runner", json: runnerRunTestsSpec },
  { specId: "runner:run-traces", appName: "Qontinui Runner", json: runnerRunTracesSpec },
  { specId: "runner:scheduled-tasks", appName: "Qontinui Runner", json: runnerScheduledTasksSpec },
  { specId: "runner:settings", appName: "Qontinui Runner", json: runnerSettingsSpec },
  {
    specId: "runner:shell-command-builder",
    appName: "Qontinui Runner",
    json: runnerShellCommandBuilderSpec,
  },
  { specId: "runner:specs-page", appName: "Qontinui Runner", json: runnerSpecsPageSpec },
  { specId: "runner:specs-page-mixed", appName: "Qontinui Runner", json: runnerSpecsPageMixedSpec },
  { specId: "runner:step-builders", appName: "Qontinui Runner", json: runnerStepBuildersSpec },
  { specId: "runner:task-builder", appName: "Qontinui Runner", json: runnerTaskBuilderSpec },
  { specId: "runner:terminal", appName: "Qontinui Runner", json: runnerTerminalSpec },
  { specId: "runner:triggers", appName: "Qontinui Runner", json: runnerTriggersSpec },
  { specId: "runner:workflows", appName: "Qontinui Runner", json: runnerWorkflowsSpec },
];

/**
 * Get all page specs as DiscoveredSpec[].
 * Returns all groups from all spec files — no category filtering.
 */
export function getAllSpecs(): DiscoveredSpec[] {
  const result: DiscoveredSpec[] = [];

  for (const { specId, appName, json } of ALL_SPECS) {
    const groups = json.groups ?? [];
    if (groups.length === 0) continue;

    result.push({
      specId,
      appName,
      config: {
        version: json.version ?? "1.0.0",
        description: json.description ?? "",
        groups,
        metadata: json.metadata,
      },
    });
  }

  return result;
}
