import { AlertTriangle, Info, Tag, XCircle } from "lucide-react";

export const SEVERITY_TOOLTIPS: Record<string, string> = {
  critical: "Must-pass. Failure means the page is fundamentally broken.",
  warning: "Should-pass. Failure indicates a degraded experience.",
  info: "Nice-to-have. Informational check, low impact if it fails.",
};

export function SeverityBadge({ severity }: { severity: string }) {
  const styles: Record<string, string> = {
    critical: "bg-red-500/15 text-red-400 border-red-500/30",
    warning: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    info: "bg-blue-500/15 text-blue-400 border-blue-500/30",
  };
  const icons: Record<string, typeof AlertTriangle> = {
    critical: XCircle,
    warning: AlertTriangle,
    info: Info,
  };
  const Icon = icons[severity] || Info;

  return (
    <span
      className={`inline-flex items-center gap-1 px-1.5 py-0.5 text-[10px] font-medium rounded border ${styles[severity] || styles.info}`}
      title={SEVERITY_TOOLTIPS[severity] || `Severity: ${severity}`}
    >
      <Icon className="w-2.5 h-2.5" />
      {severity}
    </span>
  );
}

export const CATEGORY_TOOLTIPS: Record<string, string> = {
  "element-presence": "Core UI elements exist on the page.",
  semantic: "Semantic correctness — roles, labels, and structure.",
  accessibility: "Accessibility (a11y) compliance checks.",
  "form-validation": "Form behavior and validation rules.",
  "state-consistency": "UI state is coherent across interactions.",
  navigation: "Page navigation and routing checks.",
  "cross-page-consistency": "Consistency across multiple pages.",
  "modal-dialog": "Modal and dialog behavior.",
  design: "Visual design compliance.",
  layout: "Layout and spatial relationships between elements.",
  custom: "Custom assertion category.",
};

export function CategoryBadge({ category }: { category: string }) {
  return (
    <span
      className="inline-flex items-center gap-1 px-1.5 py-0.5 text-[10px] font-medium rounded bg-white/5 text-muted-foreground border border-white/10"
      title={CATEGORY_TOOLTIPS[category] || `Category: ${category}`}
    >
      <Tag className="w-2.5 h-2.5" />
      {category}
    </span>
  );
}

export function StatCard({
  label,
  value,
  color,
}: {
  label: string;
  value: string | number;
  color?: string;
}) {
  return (
    <div className="rounded border border-white/5 bg-white/[0.02] px-3 py-2">
      <div className={`text-sm font-semibold tabular-nums ${color || "text-foreground"}`}>
        {value}
      </div>
      <div className="text-[10px] text-muted-foreground">{label}</div>
    </div>
  );
}

export const ASSERTION_TYPE_TOOLTIPS: Record<string, string> = {
  exists: "Element is present in the DOM.",
  notExists: "Element must NOT be in the DOM.",
  visible: "Element is visible on screen.",
  hidden: "Element is not visible.",
  enabled: "Element is interactive (not disabled).",
  disabled: "Element is non-interactive (disabled).",
  focused: "Element has keyboard focus.",
  checked: "Checkbox or radio is checked.",
  unchecked: "Checkbox or radio is unchecked.",
  hasText: "Element has exact text match.",
  containsText: "Element contains partial text match.",
  hasValue: "Form input has a specific value.",
  hasClass: "Element has a specific CSS class.",
  count: "Number of matching elements equals expected.",
  attribute: "Element has a specific HTML attribute value.",
  cssProperty: "Element has a specific CSS property value.",
  cssPropertyInSet: "CSS property value is in an allowed set.",
  cssPropertyRange: "CSS property value is within a numeric range.",
  tokenCompliance: "CSS property matches a design token.",
  noOverlap: "Two elements do not visually overlap (bounding box check).",
  minSpacing: "Minimum pixel gap between two elements.",
};

export const SOURCE_TOOLTIPS: Record<string, string> = {
  manual: "Hand-written by a developer.",
  auto: "Auto-generated by scanning the page.",
  "ai-generated": "Created by AI during spec generation.",
};

export const SPEC_LOAD_SOURCE_TOOLTIPS: Record<string, string> = {
  bundled: "Loaded from bundled spec files shipped with the app.",
  discovered: "Discovered from a connected app via UI Bridge.",
  file: "Loaded from a local spec file.",
};
