#!/usr/bin/env bash
#
# generate_types.sh
#
# Exports JSON Schemas from the Rust crate and generates TypeScript and Python
# type definitions. Requires:
#   - cargo (Rust toolchain)
#   - npx + json-schema-to-typescript (npm install -g json-schema-to-typescript)
#   - datamodel-code-generator (pip install datamodel-code-generator) [optional]
#
# Usage:
#   ./scripts/generate_types.sh             # Generate all types
#   ./scripts/generate_types.sh --ts-only   # TypeScript only
#   ./scripts/generate_types.sh --py-only   # Python only
#   ./scripts/generate_types.sh --dry-run   # Print schemas without generating

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCHEMAS_JSON="$PROJECT_ROOT/target/schemas.json"

TS_OUT_DIR="$PROJECT_ROOT/../src/types/generated"
PY_OUT_DIR="$PROJECT_ROOT/../../qontinui-schemas/src/qontinui_schemas/generated"

TS_ONLY=false
PY_ONLY=false
DRY_RUN=false

for arg in "$@"; do
    case "$arg" in
        --ts-only) TS_ONLY=true ;;
        --py-only) PY_ONLY=true ;;
        --dry-run) DRY_RUN=true ;;
        *) echo "Unknown argument: $arg"; exit 1 ;;
    esac
done

echo "==> Building export_schemas binary..."
cd "$PROJECT_ROOT"
cargo build --bin export_schemas --release 2>&1 | tail -5

echo "==> Exporting schemas to $SCHEMAS_JSON..."
cargo run --bin export_schemas --release -- --pretty > "$SCHEMAS_JSON"

if [ "$DRY_RUN" = true ]; then
    echo "==> Dry run: schema output:"
    cat "$SCHEMAS_JSON"
    exit 0
fi

# ── TypeScript generation ──

if [ "$PY_ONLY" = false ]; then
    echo "==> Generating TypeScript types..."
    mkdir -p "$TS_OUT_DIR"

    # Check for json-schema-to-typescript
    if ! command -v npx &> /dev/null; then
        echo "WARNING: npx not found. Skipping TypeScript generation."
        echo "  Install Node.js and run: npm install -g json-schema-to-typescript"
    else
        # Extract each schema and generate individual .d.ts files
        TYPES=$(cargo run --bin export_schemas --release -- --list)
        for TYPE_NAME in $TYPES; do
            echo "  Generating ${TYPE_NAME}.d.ts..."
            # Extract the schema for this type using node inline
            node -e "
                const schemas = require('$SCHEMAS_JSON');
                const schema = schemas['$TYPE_NAME'];
                if (schema) {
                    process.stdout.write(JSON.stringify(schema));
                }
            " | npx json2ts --input /dev/stdin --output "$TS_OUT_DIR/${TYPE_NAME}.d.ts" 2>/dev/null || \
                echo "  WARNING: Failed to generate ${TYPE_NAME}.d.ts"
        done

        # Generate barrel export
        echo "// Auto-generated by generate_types.sh — do not edit" > "$TS_OUT_DIR/index.ts"
        for TYPE_NAME in $TYPES; do
            if [ -f "$TS_OUT_DIR/${TYPE_NAME}.d.ts" ]; then
                echo "export * from './${TYPE_NAME}';" >> "$TS_OUT_DIR/index.ts"
            fi
        done

        echo "  TypeScript types written to $TS_OUT_DIR/"
    fi
fi

# ── Python generation ──

if [ "$TS_ONLY" = false ]; then
    echo "==> Generating Python (Pydantic) types..."
    mkdir -p "$PY_OUT_DIR"

    if ! command -v datamodel-codegen &> /dev/null; then
        echo "WARNING: datamodel-codegen not found. Skipping Python generation."
        echo "  Install: pip install datamodel-code-generator"
    else
        datamodel-codegen \
            --input "$SCHEMAS_JSON" \
            --input-file-type jsonschema \
            --output "$PY_OUT_DIR/models.py" \
            --output-model-type pydantic_v2.BaseModel \
            --target-python-version 3.11 \
            2>/dev/null || echo "  WARNING: Python generation failed"

        # Generate __init__.py
        echo "# Auto-generated by generate_types.sh" > "$PY_OUT_DIR/__init__.py"
        echo "from .models import *  # noqa: F401,F403" >> "$PY_OUT_DIR/__init__.py"

        echo "  Python types written to $PY_OUT_DIR/"
    fi
fi

echo "==> Done. Schema JSON: $SCHEMAS_JSON"
