/**
 * One thing the operator actually typed at a Claude Code session, projected
 * out of that session's JSONL transcript.
 */
export interface UserPrompt {
  /** Transcript record uuid — stable identity for React keys and change detection. */
  uuid: string;
  /** ISO-8601 timestamp copied verbatim from the record (may be empty). */
  timestamp: string;
  /** The prompt text, with transport envelopes stripped. */
  text: string;
}

// ── Envelope patterns ───────────────────────────────────────────────────────
//
// A transcript `user` record is NOT the same thing as "a prompt the human
// typed", and the split is made in TWO places for a reason.
//
// Records flagged machine-authored by Claude Code's own JSON fields — `isMeta`
// slash-command expansions, `isCompactSummary` continuations, `isSidechain`
// subagent turns — are dropped in Rust (`transcript::read_user_prompts`),
// because those flags exist only on the raw record and carry no text marker to
// match on. They are also the big ones; filtering them at the source is what
// keeps this payload small.
//
// What is left is envelope noise INSIDE an operator-authored record, which is
// text-shaped — so it is handled here, where it needs no DOM to test. Each
// pattern below is anchored on a marker Claude Code emits itself; nothing is
// filtered on a guess about the wording of a human prompt.

/** Injected context blocks. Never typed by the operator. */
const SYSTEM_REMINDER = /<system-reminder>[\s\S]*?<\/system-reminder>/g;
/** Output of a `!`-prefixed local command, echoed back into the conversation. */
const LOCAL_COMMAND_STDOUT = /<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g;
/** The "these were generated while running local commands" preamble. */
const LOCAL_COMMAND_CAVEAT = /<local-command-caveat>[\s\S]*?<\/local-command-caveat>/g;
/**
 * Background-task completion events the harness injects as `user` turns.
 *
 * The single biggest text-marked noise class in practice: across 19 real
 * transcripts here, 134 of the 175 records surviving every other filter (77%)
 * were these. They are not flagged `isMeta`, so the Rust side cannot catch
 * them either.
 */
const TASK_NOTIFICATION = /<task-notification>[\s\S]*?<\/task-notification>/g;
/**
 * The banner that rides with an injected notification, up to the block it
 * introduces. ANCHORED and non-global on purpose: a prompt that merely quotes
 * this banner must keep everything after it — dropping a real prompt is the
 * worse of the two failures.
 */
const SYSTEM_NOTIFICATION_BANNER =
  /^\[SYSTEM NOTIFICATION - NOT USER INPUT\][\s\S]*?(?=<task-notification>|$)/;

/** Same caveat in the older, untagged spelling. */
const BARE_CAVEAT =
  /^Caveat: The messages below were generated by the user while running local commands\.[^\n]*\n?/;

/** Slash-command envelope: `<command-name>/foo</command-name>` + args. */
const COMMAND_NAME = /<command-name>([\s\S]*?)<\/command-name>/;
const COMMAND_ARGS = /<command-args>([\s\S]*?)<\/command-args>/;
/** Residual envelope tags once name/args have been lifted out. */
const COMMAND_ENVELOPE_TAGS = /<\/?command-(?:name|args|message|contents)>/g;

/**
 * Whole-record markers the harness writes as `user` turns. Matched against the
 * FULLY stripped text, so a prompt that merely quotes one of these is kept.
 */
const SYNTHETIC_MARKERS = [
  "[Request interrupted by user]",
  "[Request interrupted by user for tool use]",
];

/** Tool-rejection turns the harness synthesizes when the operator denies a call. */
const TOOL_REJECTION =
  /^(The user doesn't want to (proceed with this tool use|take this action)|Tool use was rejected)\b/;

/**
 * Reduce one transcript record's raw text to the prompt the operator typed, or
 * `null` when the record carries no operator-authored text at all.
 *
 * Exported for tests; `extractUserPrompts` is the normal entry point.
 */
export function normalizePromptText(raw: string): string | null {
  let text = raw
    .replace(SYSTEM_REMINDER, "")
    .replace(SYSTEM_NOTIFICATION_BANNER, "")
    .replace(TASK_NOTIFICATION, "")
    .replace(LOCAL_COMMAND_STDOUT, "")
    .replace(LOCAL_COMMAND_CAVEAT, "")
    .replace(BARE_CAVEAT, "");

  // A slash command IS something the operator typed — keep it, but as the
  // `/name args` line they actually see rather than the raw envelope.
  const name = COMMAND_NAME.exec(text)?.[1]?.trim();
  if (name) {
    const args = COMMAND_ARGS.exec(text)?.[1]?.trim() ?? "";
    text = args ? `${name} ${args}` : name;
  } else {
    text = text.replace(COMMAND_ENVELOPE_TAGS, "");
  }

  text = text.trim();
  if (!text) return null;
  if (SYNTHETIC_MARKERS.includes(text)) return null;
  if (TOOL_REJECTION.test(text)) return null;
  return text;
}

/**
 * Cheap change probe: two projections are equivalent when they have the same
 * length and the same trailing uuid. Lets the poll skip a `setState` (and the
 * re-render + scroll-anchor work behind it) on the common no-new-prompt tick.
 */
export function promptsUnchanged(a: UserPrompt[], b: UserPrompt[]): boolean {
  if (a.length !== b.length) return false;
  if (a.length === 0) return true;
  return a[a.length - 1].uuid === b[b.length - 1].uuid;
}

/** `2026-08-26T14:03:11.000Z` → `14:03`. Empty/unparseable input → `""`. */
export function formatPromptTime(timestamp: string): string {
  if (!timestamp) return "";
  const d = new Date(timestamp);
  if (Number.isNaN(d.getTime())) return "";
  return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}
