import type { TranscriptMessage } from "./useTranscriptSessions";

/**
 * One thing the operator actually typed at a Claude Code session, projected
 * out of that session's JSONL transcript.
 */
export interface UserPrompt {
  /** Transcript record uuid — stable identity for React keys and change detection. */
  uuid: string;
  /** ISO-8601 timestamp copied verbatim from the record (may be empty). */
  timestamp: string;
  /** The prompt text, with transport envelopes stripped. */
  text: string;
}

// ── Envelope patterns ───────────────────────────────────────────────────────
//
// A transcript `user` record is NOT the same thing as "a prompt the human
// typed". Claude Code writes several machine-authored records under the same
// `user` role, and the Rust parser (`terminal/transcript.rs::parse_user_record`)
// only drops `tool_result` blocks — everything else arrives here as text. So
// the human/machine split is made HERE, on the text, which keeps the whole
// feature frontend-only and unit-testable.
//
// Each pattern below is anchored on a marker Claude Code emits itself; nothing
// is filtered on a guess about the wording of a human prompt.

/** Injected context blocks. Never typed by the operator. */
const SYSTEM_REMINDER = /<system-reminder>[\s\S]*?<\/system-reminder>/g;
/** Output of a `!`-prefixed local command, echoed back into the conversation. */
const LOCAL_COMMAND_STDOUT = /<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g;
/** The "these were generated while running local commands" preamble. */
const LOCAL_COMMAND_CAVEAT = /<local-command-caveat>[\s\S]*?<\/local-command-caveat>/g;
/** Same caveat in the older, untagged spelling. */
const BARE_CAVEAT =
  /^Caveat: The messages below were generated by the user while running local commands\.[^\n]*\n?/;

/** Slash-command envelope: `<command-name>/foo</command-name>` + args. */
const COMMAND_NAME = /<command-name>([\s\S]*?)<\/command-name>/;
const COMMAND_ARGS = /<command-args>([\s\S]*?)<\/command-args>/;
/** Residual envelope tags once name/args have been lifted out. */
const COMMAND_ENVELOPE_TAGS = /<\/?command-(?:name|args|message|contents)>/g;

/**
 * Whole-record markers the harness writes as `user` turns. Matched against the
 * FULLY stripped text, so a prompt that merely quotes one of these is kept.
 */
const SYNTHETIC_MARKERS = [
  "[Request interrupted by user]",
  "[Request interrupted by user for tool use]",
];

/** Tool-rejection turns the harness synthesizes when the operator denies a call. */
const TOOL_REJECTION =
  /^(The user doesn't want to (proceed with this tool use|take this action)|Tool use was rejected)\b/;

/**
 * Reduce one transcript record's raw text to the prompt the operator typed, or
 * `null` when the record carries no operator-authored text at all.
 *
 * Exported for tests; `extractUserPrompts` is the normal entry point.
 */
export function normalizePromptText(raw: string): string | null {
  let text = raw
    .replace(SYSTEM_REMINDER, "")
    .replace(LOCAL_COMMAND_STDOUT, "")
    .replace(LOCAL_COMMAND_CAVEAT, "")
    .replace(BARE_CAVEAT, "");

  // A slash command IS something the operator typed — keep it, but as the
  // `/name args` line they actually see rather than the raw envelope.
  const name = COMMAND_NAME.exec(text)?.[1]?.trim();
  if (name) {
    const args = COMMAND_ARGS.exec(text)?.[1]?.trim() ?? "";
    text = args ? `${name} ${args}` : name;
  } else {
    text = text.replace(COMMAND_ENVELOPE_TAGS, "");
  }

  text = text.trim();
  if (!text) return null;
  if (SYNTHETIC_MARKERS.includes(text)) return null;
  if (TOOL_REJECTION.test(text)) return null;
  return text;
}

/**
 * Project a session transcript down to the operator's own prompts, oldest
 * first — the order the panel renders them in, so the latest sits at the
 * bottom the way terminal output does.
 */
export function extractUserPrompts(messages: TranscriptMessage[]): UserPrompt[] {
  const out: UserPrompt[] = [];
  for (const msg of messages) {
    if (msg.msg_type !== "user") continue;
    const text = normalizePromptText(msg.text ?? "");
    if (text === null) continue;
    out.push({ uuid: msg.uuid, timestamp: msg.timestamp, text });
  }
  return out;
}

/**
 * Cheap change probe: two projections are equivalent when they have the same
 * length and the same trailing uuid. Lets the poll skip a `setState` (and the
 * re-render + scroll-anchor work behind it) on the common no-new-prompt tick.
 */
export function promptsUnchanged(a: UserPrompt[], b: UserPrompt[]): boolean {
  if (a.length !== b.length) return false;
  if (a.length === 0) return true;
  return a[a.length - 1].uuid === b[b.length - 1].uuid;
}

/** `2026-08-26T14:03:11.000Z` → `14:03`. Empty/unparseable input → `""`. */
export function formatPromptTime(timestamp: string): string {
  if (!timestamp) return "";
  const d = new Date(timestamp);
  if (Number.isNaN(d.getTime())) return "";
  return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}
