import { describe, it, expect } from "vitest";
import {
  extractUserPrompts,
  normalizePromptText,
  promptsUnchanged,
  formatPromptTime,
  type UserPrompt,
} from "./sessionPrompts";
import type { TranscriptMessage } from "./useTranscriptSessions";

function msg(over: Partial<TranscriptMessage>): TranscriptMessage {
  return {
    uuid: "u1",
    msg_type: "user",
    timestamp: "2026-08-26T14:03:11.000Z",
    text: "",
    plan_content: null,
    model: null,
    has_tool_use: false,
    ...over,
  };
}

describe("normalizePromptText", () => {
  it("keeps a plain prompt verbatim", () => {
    expect(normalizePromptText("Add a toggle button")).toBe("Add a toggle button");
  });

  it("trims surrounding whitespace", () => {
    expect(normalizePromptText("  fix the bug \n")).toBe("fix the bug");
  });

  it("strips injected system-reminder blocks", () => {
    const raw = "<system-reminder>secret context</system-reminder>\nWhat changed?";
    expect(normalizePromptText(raw)).toBe("What changed?");
  });

  it("strips multiple system-reminder blocks non-greedily", () => {
    const raw = "<system-reminder>a</system-reminder>keep<system-reminder>b</system-reminder>";
    expect(normalizePromptText(raw)).toBe("keep");
  });

  it("drops a record that is only injected context", () => {
    expect(normalizePromptText("<system-reminder>only context</system-reminder>")).toBeNull();
  });

  it("strips local-command stdout echoes", () => {
    const raw = "<local-command-stdout>Set model to Opus</local-command-stdout>";
    expect(normalizePromptText(raw)).toBeNull();
  });

  it("renders a slash command as the line the operator typed", () => {
    const raw =
      "<command-name>/model</command-name><command-message>model</command-message><command-args></command-args>";
    expect(normalizePromptText(raw)).toBe("/model");
  });

  it("appends slash-command arguments", () => {
    const raw = "<command-name>/loop</command-name><command-args>5m /babysit-prs</command-args>";
    expect(normalizePromptText(raw)).toBe("/loop 5m /babysit-prs");
  });

  it("drops the local-command caveat in both spellings", () => {
    expect(
      normalizePromptText("<local-command-caveat>Caveat: ...</local-command-caveat>"),
    ).toBeNull();
    expect(
      normalizePromptText(
        "Caveat: The messages below were generated by the user while running local commands. DO NOT respond.\nreal prompt",
      ),
    ).toBe("real prompt");
  });

  it("drops interruption markers", () => {
    expect(normalizePromptText("[Request interrupted by user]")).toBeNull();
    expect(normalizePromptText("[Request interrupted by user for tool use]")).toBeNull();
  });

  it("keeps a prompt that merely quotes an interruption marker", () => {
    expect(normalizePromptText("why did [Request interrupted by user] appear?")).toBe(
      "why did [Request interrupted by user] appear?",
    );
  });

  it("drops synthesized tool-rejection turns", () => {
    expect(
      normalizePromptText(
        "The user doesn't want to proceed with this tool use. The tool call was cancelled.",
      ),
    ).toBeNull();
  });

  it("returns null for an empty record", () => {
    expect(normalizePromptText("")).toBeNull();
    expect(normalizePromptText("   \n  ")).toBeNull();
  });
});

describe("extractUserPrompts", () => {
  it("keeps only user records, oldest first", () => {
    const out = extractUserPrompts([
      msg({ uuid: "a", text: "first" }),
      msg({ uuid: "b", msg_type: "assistant", text: "an answer" }),
      msg({ uuid: "c", text: "second" }),
    ]);
    expect(out.map((p) => p.uuid)).toEqual(["a", "c"]);
    expect(out.map((p) => p.text)).toEqual(["first", "second"]);
  });

  it("carries the record timestamp through", () => {
    const out = extractUserPrompts([
      msg({ uuid: "a", text: "hi", timestamp: "2026-08-26T09:00:00Z" }),
    ]);
    expect(out[0].timestamp).toBe("2026-08-26T09:00:00Z");
  });

  it("skips records that normalize away", () => {
    const out = extractUserPrompts([
      msg({ uuid: "a", text: "<system-reminder>ctx</system-reminder>" }),
      msg({ uuid: "b", text: "real" }),
    ]);
    expect(out.map((p) => p.uuid)).toEqual(["b"]);
  });

  it("tolerates a missing text field", () => {
    expect(extractUserPrompts([msg({ uuid: "a", text: undefined as unknown as string })])).toEqual(
      [],
    );
  });

  it("returns an empty array for an empty transcript", () => {
    expect(extractUserPrompts([])).toEqual([]);
  });
});

describe("promptsUnchanged", () => {
  const p = (uuid: string): UserPrompt => ({ uuid, timestamp: "", text: uuid });

  it("is true for two empty projections", () => {
    expect(promptsUnchanged([], [])).toBe(true);
  });

  it("is true when length and trailing uuid match", () => {
    expect(promptsUnchanged([p("a"), p("b")], [p("a"), p("b")])).toBe(true);
  });

  it("is false when a prompt was appended", () => {
    expect(promptsUnchanged([p("a")], [p("a"), p("b")])).toBe(false);
  });

  it("is false when the trailing uuid differs at equal length", () => {
    expect(promptsUnchanged([p("a"), p("b")], [p("a"), p("c")])).toBe(false);
  });
});

describe("formatPromptTime", () => {
  it("renders HH:MM zero-padded", () => {
    const d = new Date(2026, 7, 26, 9, 5);
    expect(formatPromptTime(d.toISOString())).toBe("09:05");
  });

  it("returns empty string for missing or unparseable input", () => {
    expect(formatPromptTime("")).toBe("");
    expect(formatPromptTime("not-a-date")).toBe("");
  });
});
