//! Type definitions for the knowledge graph system.
//!
//! The knowledge graph is a petgraph-backed in-memory graph that materializes
//! relationships from SQLite into a traversable structure. Nodes represent
//! entities (workflows, task runs, findings, fixes, rules, components) and
//! edges represent typed, weighted relationships between them.

use serde::Serialize;
use std::collections::HashMap;

/// Unique key for a graph node, used for HashMap lookups.
/// Format: "{kind}:{id}" e.g. "workflow:abc123", "finding:def456"
pub type NodeKey = String;

/// Every entity in the knowledge graph is a typed node.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub enum GraphNodeKind {
    Workflow,
    WorkflowVersion,
    TaskRun,
    Finding,
    Fix,
    Error,
    Component,
    Rule,
    Pattern,
    Knowledge,
    StepDef,
    PipelineAgent,
    /// A UI Bridge element that was interacted with during automation
    UIElement,
    /// A persistent observation (Engram-inspired cross-session memory)
    Observation,
    /// A reusable procedural skill (hermes-agent-inspired self-improving memory)
    Skill,
}

impl GraphNodeKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Workflow => "workflow",
            Self::WorkflowVersion => "workflow_version",
            Self::TaskRun => "task_run",
            Self::Finding => "finding",
            Self::Fix => "fix",
            Self::Error => "error",
            Self::Component => "component",
            Self::Rule => "rule",
            Self::Pattern => "pattern",
            Self::Knowledge => "knowledge",
            Self::StepDef => "step_def",
            Self::PipelineAgent => "pipeline_agent",
            Self::UIElement => "ui_element",
            Self::Observation => "observation",
            Self::Skill => "skill",
        }
    }
}

/// A node in the knowledge graph.
#[derive(Debug, Clone, Serialize)]
pub struct GraphNode {
    pub key: NodeKey,
    pub kind: GraphNodeKind,
    pub entity_id: String,
    pub label: String,
    pub weight: f64,
    pub properties: HashMap<String, serde_json::Value>,
    pub created_at: Option<String>,
}

impl GraphNode {
    pub fn new(kind: GraphNodeKind, entity_id: &str, label: &str) -> Self {
        let key = format!("{}:{}", kind.as_str(), entity_id);
        Self {
            key,
            kind,
            entity_id: entity_id.to_string(),
            label: label.to_string(),
            weight: 1.0,
            properties: HashMap::new(),
            created_at: None,
        }
    }

    pub fn with_weight(mut self, weight: f64) -> Self {
        self.weight = weight;
        self
    }

    pub fn with_property(mut self, key: &str, value: serde_json::Value) -> Self {
        self.properties.insert(key.to_string(), value);
        self
    }

    pub fn with_created_at(mut self, created_at: &str) -> Self {
        self.created_at = Some(created_at.to_string());
        self
    }
}

/// Typed, weighted, directed edges.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub enum GraphEdgeKind {
    /// Finding/error caused a fix to be created
    Caused,
    /// Fix resolved a finding/error
    Resolved,
    /// Finding was detected during a task run
    DetectedDuring,
    /// Step was produced by a pipeline agent
    ProducedBy,
    /// Workflow was influenced by a rule or knowledge entry
    InfluencedBy,
    /// Workflow version evolved from a prior version
    EvolvedFrom,
    /// Two findings/errors co-occurred in the same run
    CoOccursWith,
    /// Fix/finding impacts a component
    ImpactsComponent,
    /// Pattern recurred as a finding
    RecurredAs,
    /// Task run belongs to a workflow
    BelongsTo,
    /// Fix was applied in a task run
    AppliedIn,
    /// Workflow was generated by a task run
    GeneratedBy,
    /// Step was built by a pipeline agent
    BuiltBy,
    /// Step touches a component (file/module)
    TouchesComponent,
    /// Task run interacted with a UI Bridge element
    InteractedWith,
    /// Observation informed a workflow decision or fix
    InformedBy,
    /// Observation was learned from a task run
    LearnedFrom,
    /// Skill was used in a task run (applied during agentic phase)
    UsedIn,
    /// Skill was derived from a fix or finding pattern
    DerivedFrom,
    /// Skill supersedes an older, less effective skill
    Supersedes,
}

impl GraphEdgeKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Caused => "caused",
            Self::Resolved => "resolved",
            Self::DetectedDuring => "detected_during",
            Self::ProducedBy => "produced_by",
            Self::InfluencedBy => "influenced_by",
            Self::EvolvedFrom => "evolved_from",
            Self::CoOccursWith => "co_occurs_with",
            Self::ImpactsComponent => "impacts_component",
            Self::RecurredAs => "recurred_as",
            Self::BelongsTo => "belongs_to",
            Self::AppliedIn => "applied_in",
            Self::GeneratedBy => "generated_by",
            Self::BuiltBy => "built_by",
            Self::TouchesComponent => "touches_component",
            Self::InteractedWith => "interacted_with",
            Self::InformedBy => "informed_by",
            Self::LearnedFrom => "learned_from",
            Self::UsedIn => "used_in",
            Self::DerivedFrom => "derived_from",
            Self::Supersedes => "supersedes",
        }
    }
}

/// An edge in the knowledge graph.
#[derive(Debug, Clone, Serialize)]
pub struct GraphEdge {
    pub kind: GraphEdgeKind,
    pub weight: f64,
    pub label: Option<String>,
    pub metadata: Option<serde_json::Value>,
}

impl GraphEdge {
    pub fn new(kind: GraphEdgeKind) -> Self {
        Self {
            kind,
            weight: 1.0,
            label: None,
            metadata: None,
        }
    }

    pub fn with_weight(mut self, weight: f64) -> Self {
        self.weight = weight;
        self
    }

    pub fn with_label(mut self, label: &str) -> Self {
        self.label = Some(label.to_string());
        self
    }

    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = Some(metadata);
        self
    }
}

/// A path through the graph (sequence of alternating nodes and edges).
#[derive(Debug, Clone, Serialize)]
pub struct GraphPath {
    pub nodes: Vec<GraphNode>,
    pub edges: Vec<GraphEdge>,
    pub total_weight: f64,
}

impl GraphPath {
    pub fn len(&self) -> usize {
        self.edges.len()
    }

    pub fn is_empty(&self) -> bool {
        self.edges.is_empty()
    }
}

/// N-hop neighborhood of a node.
#[derive(Debug, Clone, Serialize)]
pub struct GraphNeighborhood {
    pub center: GraphNode,
    pub neighbors: Vec<NeighborEntry>,
    pub depth: u32,
}

#[derive(Debug, Clone, Serialize)]
pub struct NeighborEntry {
    pub node: GraphNode,
    pub edge: GraphEdge,
    pub direction: EdgeDirection,
    pub distance: u32,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub enum EdgeDirection {
    Outgoing,
    Incoming,
}

/// Summary statistics for the graph.
#[derive(Debug, Clone, Serialize)]
pub struct GraphSummary {
    pub total_nodes: usize,
    pub total_edges: usize,
    pub nodes_by_kind: HashMap<String, usize>,
    pub edges_by_kind: HashMap<String, usize>,
    pub most_connected: Vec<(String, usize)>,
    pub built_at: String,
    pub workflow_scope: Option<String>,
}
