/**
 * Selector Generator for UI Bridge Elements
 *
 * Generates various selector strategies and code snippets for automation frameworks.
 * Part of P1.3 implementation for Element Description Panel improvements.
 */

import type { ExternalElement } from "../../hooks/useExternalUIBridge";

/**
 * Result of a selector generation with metadata
 */
export interface SelectorResult {
  /** The generated selector string */
  selector: string;
  /** Type of selector */
  type: "css" | "xpath" | "testId" | "accessible";
  /** Reliability score 0-100 (higher = more stable) */
  reliability: number;
  /** Human-readable description of the selector strategy */
  description: string;
  /** Whether this selector is likely to be unique on the page */
  isLikelyUnique: boolean;
}

/**
 * Generate a CSS selector from element data
 *
 * Priority:
 * 1. data-testid or data-ui-id (most reliable for testing)
 * 2. ID attribute
 * 3. Unique class combination
 * 4. Tag + attributes
 * 5. Fallback to element's stored selector
 */
export function generateCssSelector(element: ExternalElement): SelectorResult {
  // Check for test IDs first (most reliable)
  const testId =
    element.dataAttributes?.["testid"] ||
    element.dataAttributes?.["test-id"] ||
    element.dataAttributes?.["ui-id"];

  if (testId) {
    const attr = element.dataAttributes?.["testid"]
      ? "data-testid"
      : element.dataAttributes?.["test-id"]
        ? "data-test-id"
        : "data-ui-id";
    return {
      selector: `[${attr}="${testId}"]`,
      type: "css",
      reliability: 95,
      description: "Test ID selector (recommended for automation)",
      isLikelyUnique: true,
    };
  }

  // Check for element ID
  if (element.id && !element.id.startsWith("@e") && !element.id.match(/^[a-f0-9-]{36}$/i)) {
    // Avoid auto-generated IDs (UUIDs, @e references)
    const isAutoGenerated =
      element.id.includes(":") || element.id.match(/^\d+$/) || element.id.match(/^_/);
    if (!isAutoGenerated) {
      return {
        selector: `#${CSS.escape(element.id)}`,
        type: "css",
        reliability: 85,
        description: "ID selector",
        isLikelyUnique: true,
      };
    }
  }

  // Check for unique class combinations
  if (element.classes && element.classes.length > 0) {
    const meaningfulClasses = element.classes.filter(
      (c) =>
        !c.match(/^[a-z]{1,2}\d+$/i) && // Exclude minified classes like "a1", "b23"
        !c.match(/^_/) && // Exclude underscore-prefixed
        !c.includes("--") && // Exclude BEM modifiers in isolation
        c.length > 2,
    );

    if (meaningfulClasses.length > 0) {
      const classSelector = meaningfulClasses.slice(0, 3).map((c) => `.${CSS.escape(c)}`);
      const tagPrefix = element.tagName.toLowerCase();
      return {
        selector: `${tagPrefix}${classSelector.join("")}`,
        type: "css",
        reliability: 60,
        description: "Tag + class combination",
        isLikelyUnique: meaningfulClasses.length >= 2,
      };
    }
  }

  // Build attribute-based selector
  const tag = element.tagName.toLowerCase();
  const attrs: string[] = [];

  if (element.type && element.inputType) {
    attrs.push(`type="${element.inputType}"`);
  }
  if (element.name) {
    attrs.push(`name="${element.name}"`);
  }
  if (element.placeholder) {
    attrs.push(`placeholder="${element.placeholder}"`);
  }
  if (element.accessibility?.ariaLabel) {
    attrs.push(`aria-label="${element.accessibility.ariaLabel}"`);
  }

  if (attrs.length > 0) {
    return {
      selector: `${tag}[${attrs.join("][")}]`,
      type: "css",
      reliability: 50,
      description: "Tag + attribute selector",
      isLikelyUnique: attrs.length >= 2,
    };
  }

  // Use the element's stored selector as fallback
  if (element.selector) {
    return {
      selector: element.selector,
      type: "css",
      reliability: 40,
      description: "Computed CSS selector",
      isLikelyUnique: true,
    };
  }

  // Ultimate fallback: just the tag name
  return {
    selector: tag,
    type: "css",
    reliability: 10,
    description: "Tag name only (not unique)",
    isLikelyUnique: false,
  };
}

/**
 * Generate an XPath selector from element data
 *
 * Priority:
 * 1. Text-based XPath for buttons/links
 * 2. Attribute-based XPath
 * 3. Fallback to stored xpath
 */
export function generateXPath(element: ExternalElement): SelectorResult {
  // Use stored xpath if available
  if (element.xpath) {
    return {
      selector: element.xpath,
      type: "xpath",
      reliability: 75,
      description: "Computed XPath",
      isLikelyUnique: true,
    };
  }

  const tag = element.tagName.toLowerCase();

  // For buttons and links, text-based XPath is often most reliable
  if ((element.type === "button" || element.type === "link") && element.text) {
    const escapedText = element.text.replace(/'/g, "\\'");
    return {
      selector: `//${tag}[normalize-space(text())='${escapedText}']`,
      type: "xpath",
      reliability: 70,
      description: "Text-based XPath",
      isLikelyUnique: true,
    };
  }

  // Check for accessible name
  if (element.accessibility?.accessibleName) {
    const escapedName = element.accessibility.accessibleName.replace(/'/g, "\\'");
    return {
      selector: `//${tag}[@aria-label='${escapedName}' or normalize-space(.)='${escapedName}']`,
      type: "xpath",
      reliability: 65,
      description: "Accessible name XPath",
      isLikelyUnique: true,
    };
  }

  // Build attribute-based XPath
  const conditions: string[] = [];

  if (element.id && !element.id.startsWith("@e")) {
    conditions.push(`@id='${element.id}'`);
  }
  if (element.name) {
    conditions.push(`@name='${element.name}'`);
  }
  if (element.placeholder) {
    conditions.push(`@placeholder='${element.placeholder}'`);
  }

  if (conditions.length > 0) {
    return {
      selector: `//${tag}[${conditions.join(" and ")}]`,
      type: "xpath",
      reliability: 55,
      description: "Attribute-based XPath",
      isLikelyUnique: conditions.length >= 2,
    };
  }

  // Fallback to indexed XPath
  return {
    selector: `//${tag}`,
    type: "xpath",
    reliability: 10,
    description: "Tag name only (not unique)",
    isLikelyUnique: false,
  };
}

/**
 * Generate a test ID selector if available
 *
 * Looks for common test ID data attributes
 */
export function generateTestIdSelector(element: ExternalElement): SelectorResult | null {
  const testIdAttrs = ["testid", "test-id", "ui-id", "cy", "pw"];

  for (const attr of testIdAttrs) {
    const value = element.dataAttributes?.[attr];
    if (value) {
      const fullAttr = attr === "testid" ? "data-testid" : `data-${attr}`;
      return {
        selector: `[${fullAttr}="${value}"]`,
        type: "testId",
        reliability: 95,
        description: `Test ID (${fullAttr})`,
        isLikelyUnique: true,
      };
    }
  }

  return null;
}

/**
 * Generate an accessible selector based on ARIA attributes
 *
 * Uses role + accessible name for semantic selection
 */
export function generateAccessibleSelector(element: ExternalElement): SelectorResult | null {
  const role = element.accessibility?.role || element.role;
  const name = element.accessibility?.accessibleName || element.accessibleName;

  if (!role && !name) {
    return null;
  }

  // Build getByRole-style selector info
  if (role && name) {
    return {
      selector: `role=${role}[name="${name}"]`,
      type: "accessible",
      reliability: 85,
      description: "ARIA role + accessible name",
      isLikelyUnique: true,
    };
  }

  if (role) {
    return {
      selector: `role=${role}`,
      type: "accessible",
      reliability: 40,
      description: "ARIA role only",
      isLikelyUnique: false,
    };
  }

  if (name) {
    return {
      selector: `name="${name}"`,
      type: "accessible",
      reliability: 60,
      description: "Accessible name only",
      isLikelyUnique: false,
    };
  }

  return null;
}

/**
 * Code snippet generation for automation frameworks
 */

export type AutomationAction = "click" | "fill" | "type" | "hover" | "focus" | "check" | "select";

interface CodeSnippetResult {
  code: string;
  framework: string;
  language: string;
}

/**
 * Generate Playwright code snippet
 */
export function generatePlaywrightCode(
  element: ExternalElement,
  action: AutomationAction = "click",
  value?: string,
): CodeSnippetResult {
  const cssResult = generateCssSelector(element);
  const accessibleResult = generateAccessibleSelector(element);

  // Prefer accessible selectors for Playwright (better stability)
  let locator: string;
  if (accessibleResult && accessibleResult.reliability >= 70) {
    const role = element.accessibility?.role || element.role;
    const name = element.accessibility?.accessibleName || element.accessibleName;
    if (role && name) {
      locator = `page.getByRole('${role}', { name: '${name.replace(/'/g, "\\'")}' })`;
    } else if (name) {
      locator = `page.getByText('${name.replace(/'/g, "\\'")}')`;
    } else {
      locator = `page.locator('${cssResult.selector.replace(/'/g, "\\'")}')`;
    }
  } else {
    locator = `page.locator('${cssResult.selector.replace(/'/g, "\\'")}')`;
  }

  let code: string;
  switch (action) {
    case "fill":
      code = `await ${locator}.fill('${value || ""}');`;
      break;
    case "type":
      code = `await ${locator}.type('${value || ""}');`;
      break;
    case "hover":
      code = `await ${locator}.hover();`;
      break;
    case "focus":
      code = `await ${locator}.focus();`;
      break;
    case "check":
      code = `await ${locator}.check();`;
      break;
    case "select":
      code = `await ${locator}.selectOption('${value || ""}');`;
      break;
    case "click":
    default:
      code = `await ${locator}.click();`;
  }

  return {
    code,
    framework: "Playwright",
    language: "typescript",
  };
}

/**
 * Generate Puppeteer code snippet
 */
export function generatePuppeteerCode(
  element: ExternalElement,
  action: AutomationAction = "click",
  value?: string,
): CodeSnippetResult {
  const cssResult = generateCssSelector(element);
  const selector = cssResult.selector.replace(/'/g, "\\'");

  let code: string;
  switch (action) {
    case "fill":
    case "type":
      code = `await page.type('${selector}', '${value || ""}');`;
      break;
    case "hover":
      code = `await page.hover('${selector}');`;
      break;
    case "focus":
      code = `await page.focus('${selector}');`;
      break;
    case "select":
      code = `await page.select('${selector}', '${value || ""}');`;
      break;
    case "click":
    default:
      code = `await page.click('${selector}');`;
  }

  return {
    code,
    framework: "Puppeteer",
    language: "typescript",
  };
}

/**
 * Generate Cypress code snippet
 */
export function generateCypressCode(
  element: ExternalElement,
  action: AutomationAction = "click",
  value?: string,
): CodeSnippetResult {
  const cssResult = generateCssSelector(element);
  const selector = cssResult.selector.replace(/'/g, "\\'");

  let code: string;
  switch (action) {
    case "fill":
    case "type":
      code = `cy.get('${selector}').type('${value || ""}');`;
      break;
    case "hover":
      code = `cy.get('${selector}').trigger('mouseover');`;
      break;
    case "focus":
      code = `cy.get('${selector}').focus();`;
      break;
    case "check":
      code = `cy.get('${selector}').check();`;
      break;
    case "select":
      code = `cy.get('${selector}').select('${value || ""}');`;
      break;
    case "click":
    default:
      code = `cy.get('${selector}').click();`;
  }

  return {
    code,
    framework: "Cypress",
    language: "typescript",
  };
}

/**
 * Generate Qontinui action code
 */
export function generateQontinuiCode(
  element: ExternalElement,
  action: AutomationAction = "click",
  value?: string,
): CodeSnippetResult {
  // Use the element's ref (e.g., @e1) if available, otherwise fall back to ID
  const target = element.ref || `@${element.id}`;

  let code: string;
  switch (action) {
    case "fill":
    case "type":
      code = `- action: type\n  target: "${target}"\n  value: "${value || ""}"`;
      break;
    case "hover":
      code = `- action: hover\n  target: "${target}"`;
      break;
    case "focus":
      code = `- action: focus\n  target: "${target}"`;
      break;
    case "check":
      code = `- action: check\n  target: "${target}"`;
      break;
    case "select":
      code = `- action: select\n  target: "${target}"\n  value: "${value || ""}"`;
      break;
    case "click":
    default:
      code = `- action: click\n  target: "${target}"`;
  }

  return {
    code,
    framework: "Qontinui",
    language: "yaml",
  };
}

/**
 * Generate Selenium WebDriver code snippet
 */
export function generateSeleniumCode(
  element: ExternalElement,
  action: AutomationAction = "click",
  value?: string,
): CodeSnippetResult {
  const cssResult = generateCssSelector(element);
  const selector = cssResult.selector.replace(/"/g, '\\"');

  let code: string;
  switch (action) {
    case "fill":
    case "type":
      code = `driver.find_element(By.CSS_SELECTOR, "${selector}").send_keys("${value || ""}")`;
      break;
    case "hover":
      code = `ActionChains(driver).move_to_element(driver.find_element(By.CSS_SELECTOR, "${selector}")).perform()`;
      break;
    case "focus":
      code = `driver.find_element(By.CSS_SELECTOR, "${selector}").send_keys("")`;
      break;
    case "click":
    default:
      code = `driver.find_element(By.CSS_SELECTOR, "${selector}").click()`;
  }

  return {
    code,
    framework: "Selenium",
    language: "python",
  };
}

/**
 * Get all available selectors for an element
 */
export function getAllSelectors(element: ExternalElement): SelectorResult[] {
  const results: SelectorResult[] = [];

  // Always include CSS selector
  results.push(generateCssSelector(element));

  // Always include XPath
  results.push(generateXPath(element));

  // Include test ID if available
  const testIdResult = generateTestIdSelector(element);
  if (testIdResult) {
    results.push(testIdResult);
  }

  // Include accessible selector if available
  const accessibleResult = generateAccessibleSelector(element);
  if (accessibleResult) {
    results.push(accessibleResult);
  }

  // Sort by reliability (highest first)
  results.sort((a, b) => b.reliability - a.reliability);

  return results;
}

/**
 * Get the best selector for an element
 */
export function getBestSelector(element: ExternalElement): SelectorResult {
  const all = getAllSelectors(element);
  return all[0];
}
