/**
 * Knowledge Graph Tutorial
 *
 * Informational tutorial explaining the runner's petgraph-backed knowledge graph
 * system — what it is, how it's built, and how it connects findings, fixes,
 * workflows, UI elements, and cross-run patterns into a traversable structure.
 */

import type { Tutorial } from "../../../types/tutorial";

export const knowledgeGraphTutorial: Tutorial = {
  id: "knowledge-graph",
  title: "Understanding the Knowledge Graph",
  description:
    "Deep dive into the runner's knowledge graph — how it connects workflows, findings, fixes, and UI elements into a traversable structure for causal analysis and cross-run learning.",
  duration: "12 minutes",
  difficulty: "advanced",
  mode: "contextual",
  focusPage: "help",
  category: "Architecture",
  tags: ["knowledge-graph", "architecture", "cross-run", "reflection", "advanced"],
  prerequisites: ["getting-started"],
  learningObjectives: [
    "Understand the knowledge graph's purpose and data model",
    "Know the 13 node types and 15 edge types",
    "Understand how the graph is built from SQLite tables",
    "See how cross-run patterns detect recurring issues",
    "Learn how UI Bridge interactions feed into the graph",
    "Understand causal tracing for root cause analysis",
  ],
  steps: [
    {
      id: "intro",
      title: "What is the Knowledge Graph?",
      content: `The **Knowledge Graph** is an in-memory graph structure (powered by petgraph) that materializes relationships from the runner's SQLite database into a traversable network.

**Why does it exist?**

When the runner executes workflows across multiple runs, it accumulates findings, fixes, errors, and interaction data. The knowledge graph connects these into a single structure where you can ask questions like:

- *"Why does this element keep failing?"*
- *"Which fix resolved this recurring error?"*
- *"What workflow changes caused this regression?"*

It's the runner's **institutional memory** — turning isolated data points into connected knowledge.`,
      estimatedDuration: 1,
      tips: [
        "The graph is rebuilt on demand, not kept permanently in memory",
        "It can be scoped to a single workflow for efficiency",
      ],
    },
    {
      id: "node-types",
      title: "Node Types — The Entities",
      content: `The graph contains **13 node types**, each representing a distinct entity in the system:

| Type | What it represents |
|------|--------------------|
| **Workflow** | A workflow definition (name, category) |
| **WorkflowVersion** | A snapshot of a workflow at a point in time |
| **TaskRun** | A single execution of a workflow |
| **Finding** | An issue discovered during a run |
| **Fix** | A solution applied to address a finding |
| **Error** | An error event grouped by signature hash |
| **Component** | An architecture component (file/module) |
| **Rule** | A generation rule that influences workflow construction |
| **Pattern** | A cross-run recurring pattern |
| **Knowledge** | A learned insight from tasks |
| **StepDef** | A workflow step definition |
| **PipelineAgent** | An agent that generates steps |
| **UIElement** | A UI Bridge element interacted with during automation |`,
      estimatedDuration: 1,
      details: `Each node has a **key** (format: \`{kind}:{id}\`), a **weight** (used for ranking), and **properties** (arbitrary JSON metadata).

For example, a Finding node might have:
\`\`\`
key: "finding:abc123"
weight: 3.0  (high severity)
properties: { severity: "high", category: "selector" }
\`\`\`

UIElement nodes are capped at **100 per workflow** to respect memory budgets. They include interaction_count and success_rate properties.`,
    },
    {
      id: "edge-types",
      title: "Edge Types — The Relationships",
      content: `Edges are **typed, weighted, and directed**. There are **15 edge types** that encode different relationships:

**Causal edges:**
- **Caused** — Finding/error caused a fix to be created
- **Resolved** — Fix resolved a finding/error
- **DetectedDuring** — Finding was detected during a task run

**Structural edges:**
- **BelongsTo** — TaskRun belongs to a workflow
- **EvolvedFrom** — WorkflowVersion evolved from a prior version
- **BuiltBy** — Step was built by a pipeline agent
- **GeneratedBy** — WorkflowVersion was generated by a TaskRun

**Analysis edges:**
- **CoOccursWith** — Two findings co-occurred in the same run
- **ImpactsComponent** — Fix/finding impacts a component
- **RecurredAs** — Pattern recurred as a finding
- **AppliedIn** — Fix was applied in a task run
- **InfluencedBy** — Workflow was influenced by a rule
- **TouchesComponent** — Step touches a component
- **InteractedWith** — TaskRun interacted with a UI element`,
      estimatedDuration: 1,
      details: `Edge weights encode strength:
- **Resolved edges**: weight 2.0 (strong positive signal)
- **AppliedIn edges**: weight varies by outcome — resolved=2.0, ineffective=0.5
- **InteractedWith edges**: weight = success_rate * interaction_count

The weight system allows traversal algorithms to prefer high-confidence paths.`,
    },
    {
      id: "building-the-graph",
      title: "How the Graph is Built",
      content: `The graph is built on-demand from **16+ database tables** by the \`build_from_db()\` function in \`reflection/graph_engine.rs\`.

**Build process:**
1. **Load nodes** — Query each entity table, create typed nodes
2. **Load edges** — Query relationship tables, create directed edges
3. **Scope by workflow** — Optionally filter to a single workflow name

**Key tables queried:**
- \`unified_workflows\`, \`workflow_versions\` — Workflow entities
- \`task_runs\` — Execution instances
- \`task_run_findings\`, \`reflection_fixes\` — Issues and solutions
- \`error_events\` — Errors grouped by signature
- \`cross_run_patterns\` — Recurring patterns
- \`step_provenance\` — Step generation history
- \`ui_bridge_events\` — UI interaction data

The graph is **not persisted** — it's rebuilt each time it's needed. This ensures it always reflects the latest data.`,
      estimatedDuration: 1,
      tips: [
        "Building the full graph queries 16+ tables — scope by workflow_name when possible",
        "UIElement nodes are loaded from ui_bridge_events, capped at 100 per workflow",
        "Graph traversals are depth-limited (max 5-10 hops) to prevent memory explosion",
      ],
    },
    {
      id: "graph-queries",
      title: "Querying the Graph",
      content: `The graph supports several query types, exposed via **MCP HTTP endpoints**:

**Discovery:**
- \`GET /graph/summary\` — Node/edge counts, top-10 most-connected nodes
- \`GET /graph/search?q=...\` — Unified text search across all entity types

**Traversal:**
- \`GET /graph/neighborhood\` — N-hop neighborhood of a node
- \`GET /graph/paths\` — Find paths between two nodes (BFS)
- \`GET /graph/root-causes\` — Trace backward along causal edges
- \`GET /graph/impact\` — Trace forward to see downstream effects

**Analysis:**
- \`GET /graph/cross-run-patterns\` — Recurring findings and fix oscillations
- \`GET /graph/similar-errors\` — Fuzzy match errors by trigram + embedding
- \`GET /graph/effectiveness\` — Rank fixes/rules by effectiveness score`,
      estimatedDuration: 1,
      details: `**Path finding** uses BFS with a max depth of 10 and returns up to 10 paths.

**Root cause tracing** uses DFS backward along Caused/DetectedDuring edges — it follows the chain from an error back to its origin.

**Impact tracing** follows forward along Resolved/ImpactsComponent/AppliedIn edges — it shows the downstream effects of a fix or finding.

**Effectiveness ranking** computes:
\`score = (resolved_count * 2 - regression_count * 3) / total_edges\`

A fix with score > 0 is net positive; negative means it caused more regressions than it resolved.`,
    },
    {
      id: "cross-run-patterns",
      title: "Cross-Run Pattern Detection",
      content: `One of the graph's most powerful features is **cross-run pattern detection** — analyzing data across multiple workflow runs to find recurring issues.

**Two pattern types:**

**Recurring Findings** — The same finding (identified by signature hash) appears in 3+ runs. This means a persistent issue that individual fixes haven't resolved.

**Fix Oscillations** — A fix is applied and marked "effective," but the same finding recurs in a later run. This indicates a superficial fix that treats symptoms, not root causes.

**What the system does automatically:**
- Detects patterns after each run via \`detect_recurring_findings()\` and \`detect_fix_oscillations()\`
- Auto-disables ineffective generation rules (threshold: 3 "no_effect" with 0 "prevented_error")
- Auto-applies known-good fixes for recurring findings

Patterns are stored in the \`cross_run_patterns\` table with status: **active**, **resolved**, or **suppressed**.`,
      estimatedDuration: 1,
      targetElement: {
        selector: '[data-tutorial-id="sidebar-reflection"]',
        highlightType: "border",
        position: "right",
        scrollIntoView: true,
      },
      tips: [
        "View cross-run patterns on the Reflection Dashboard",
        "Active patterns (red badges) need attention",
        "Resolved patterns (green badges) confirm a fix worked",
        "The system auto-disables rules that consistently have no effect",
      ],
    },
    {
      id: "fuzzy-matching",
      title: "Fuzzy Matching and Error Similarity",
      content: `Not all errors are exact duplicates. The graph includes a **fuzzy matching engine** that finds similar errors even when the exact text differs.

**Two similarity methods:**

**Trigram Similarity** (always available)
- Computes Dice coefficient over 3-character n-grams
- Works purely on text — no AI required
- Default threshold: 0.6

**Embedding Similarity** (when vectors available)
- Cosine similarity on error message embeddings
- More semantically aware (catches paraphrased errors)
- Higher threshold: 0.8

**How it's used:**
- \`find_similar_errors()\` returns errors ranked by similarity
- \`predict_fix_fuzzy()\` finds fixes that resolved similar errors in the past
- \`generalize_fix()\` broadens a fix's applicability when it's been reused 2+ times

This allows the system to suggest fixes for errors it hasn't seen before, based on similar past errors.`,
      estimatedDuration: 1,
      details: `**Confidence calculation for predicted fixes:**
\`\`\`
confidence = similarity * (1.0 + reuse_count * 0.1).min(1.5)
\`\`\`

The more times a fix has been reused, the higher the confidence. The match method is recorded as "embedding" (>0.8 similarity), "trigram", or "exact".

When a fix reaches reuse_count >= 2, \`generalize_fix()\` promotes it to 'universal' reflection_scope, making it available across all workflows.`,
    },
    {
      id: "ui-bridge-integration",
      title: "UI Bridge Integration",
      content: `The knowledge graph connects to the **UI Bridge** through two new node/edge types:

**UIElement nodes** — Represent UI elements that were interacted with during automation. Each node stores:
- \`interaction_count\` — How many times this element was used
- \`success_rate\` — What fraction of interactions succeeded
- \`flaky\` flag — Whether the element is unreliable (< 95% success)

**InteractedWith edges** — Connect TaskRun nodes to UIElement nodes, weighted by \`success_rate * interaction_count\`.

**What this enables:**
- **Failure chain tracing** — Follow edges from a failing UI element back through task runs to the workflow and rules that generated the automation
- **Element reliability scoring** — Aggregate success rates across runs
- **CTR confidence seeding** — Push reliability data to the SDK's Central Target Registry

The \`GET /graph/ui-failure-chain?element_id=X\` endpoint traces these connections to answer: *"Why does this button keep failing to click?"*`,
      estimatedDuration: 1,
      tips: [
        "UI interactions are persisted when actions use the ?task_run_id= query parameter",
        "Element reliability data is pushed to SDK apps on connect for CTR pre-seeding",
        "The Automation Health dashboard visualizes this data",
      ],
    },
    {
      id: "unified-search",
      title: "Unified Search",
      content: `The graph includes a **unified search** that queries across all data stores in one call.

\`GET /graph/search?q=login&limit=20\`

**Searches 7 entity types:**
1. \`task_run_findings\` — Finding titles and descriptions
2. \`reflection_fixes\` — Fix types and descriptions
3. \`task_knowledge\` — Learned knowledge content
4. \`error_events\` — Error messages and types
5. \`generation_rules\` — Rule titles and content
6. \`unified_workflows\` — Workflow names and descriptions
7. \`ui_bridge_elements\` — Element IDs, labels, and text content

**Scoring:**
- Title match: relevance 1.0
- Description/content match: relevance 0.7
- Results sorted by relevance, capped at the requested limit

This provides a single search box that finds anything in the system.`,
      estimatedDuration: 1,
    },
    {
      id: "step-provenance",
      title: "Step Provenance and Pipeline Instrumentation",
      content: `The graph tracks **who generated each workflow step** and what happened during generation.

**Step Provenance** records:
- Which **pipeline agent** generated the step (discovery, builder, fixer, hardener, verifier)
- The **phase** (setup, verification, agentic, completion)
- The **generation iteration** number
- The original and final step JSON (before/after fixer modifications)
- **UI Bridge event IDs** — which UI interactions occurred during this step

**Pipeline Events** record:
- Event type and phase
- Duration and token count per phase
- Validation error counts before and after

This creates a full audit trail: for any workflow step, you can trace back to the agent that created it, the rules that influenced it, and the UI interactions that occurred during its execution.`,
      estimatedDuration: 1,
      details: `The **Step Provenance Timeline** component (on the Reflection Dashboard) visualizes this data as a vertical timeline with color-coded dots per agent:

- Blue = discovery agent
- Green = builder agent
- Orange = fixer agent
- Purple = hardener agent
- Cyan = verifier agent

Steps with UI Bridge interactions show a count badge (e.g., "3 UI interactions").`,
    },
    {
      id: "automation-health",
      title: "Automation Health Dashboard",
      content: `All this data feeds into the **Automation Health Dashboard** — a composite view of UI Bridge automation quality.

**Health Score** (0-100):
\`\`\`
score = 0.30 * element_success_rate
      + 0.25 * (1 - regression_rate)
      + 0.25 * (1 - stall_frequency)
      + 0.20 base
\`\`\`

**9 analytics panels:**
- Health Score gauge with breakdown metrics
- Improvement Recommendations (rule-based)
- Element Reliability heatmap
- Action Performance Baselines (latency per action type)
- Failure Taxonomy (error clusters)
- Automation Regressions (degraded elements)
- Stall Frequency by pattern type
- Intervention Effectiveness (what resolved stalls)
- Annotation Gaps (elements needing data-testid)

All panels are backed by **13 MCP endpoints** under \`/ui-bridge/analytics/*\` and use **17 SQL analytics queries** against the \`ui_bridge_events\` table.`,
      estimatedDuration: 1,
      targetElement: {
        selector: '[data-tutorial-id="sidebar-automation-health"]',
        highlightType: "pulse",
        position: "right",
        scrollIntoView: true,
      },
      tips: [
        "Navigate to OBSERVE → Automation Health in the sidebar",
        "The time range selector (24h/7d/30d) filters all panels",
        "A declining health score means automation quality is degrading",
      ],
    },
    {
      id: "mental-model",
      title: "Mental Model Summary",
      content: `Here's how all the pieces connect:

**Data flows in:**
1. Workflow execution → task_runs, findings, fixes, errors
2. UI Bridge actions → ui_bridge_events (with element_id, success, duration)
3. Workflow generation → step_provenance, pipeline_events, rule_influence
4. Cross-run analysis → cross_run_patterns

**The graph materializes these relationships:**
\`\`\`
UIElement ← InteractedWith ← TaskRun → BelongsTo → Workflow
                                ↓
                         DetectedDuring
                                ↓
                           Finding → Caused → Fix
                                         ↓
                                    AppliedIn → TaskRun
\`\`\`

**Intelligence flows out:**
- Cross-run patterns detect recurring issues
- Fuzzy matching predicts fixes for new errors
- Root cause tracing explains failure chains
- Automation health score tracks quality over time
- CTR confidence seeding improves selector reliability

The knowledge graph is the **connective tissue** that turns raw execution data into actionable intelligence.`,
      estimatedDuration: 1,
      tips: [
        "The graph is rebuilt on demand — always reflects the latest data",
        "All 16 MCP endpoints are available via HTTP on port 9876",
        "The system is SQLite-first with PostgreSQL migration planned",
      ],
    },
  ],
};
