#!/usr/bin/env bash
#
# gen-events-attribution.sh — "is this drift THIS push's fault?"
#
# Sourced by `.pre-commit-hooks/gen-events-drift.sh`. Split into its own file
# so the decision can be tested against throwaway git repos without a Rust
# toolchain, a schemas checkout or a ~minute release build —
# `gen-events-drift-attribution-test.sh` does exactly that.
#
# THE PROBLEM THIS SOLVES
#
# The drift hook compares freshly generated bindings against
# `qontinui-schemas/ts/src/generated/`. That baseline is a BUILD ARTIFACT in a
# shared checkout, not a committed contract: it is regenerated by hand, rarely,
# by whoever last needed it. So it lags this repo's Rust by however many
# schema-touching commits have landed since. Every pusher after that point
# generates fresh bindings, diffs them against the lagging artifact, and is
# told "Your Rust changes would move ts/src/generated" — about a change they
# did not make.
#
# The drift is REAL. The blame is not. This is a false-attribution bug, not a
# false-detection one, and it is fixed by splitting the verdict rather than by
# weakening the check.
#
# It bites hardest at pre-push, where pre-commit computes the changed-file set
# over the whole pushed RANGE. On a long-lived or rebased branch that range is
# old-base..main, so a PEER's schema commit is what fires the hook while the
# pusher's own diff is (say) frontend-only.
#
# THE PREDICATE
#
# Compare the push's own commits — `merge-base(HEAD, upstream)..HEAD` — plus
# its uncommitted working tree, against the set of paths in THIS repo whose
# content can move `schemas.json`. If NONE of them is touched, then the very
# inputs that produced this diff are already on the upstream branch, so the
# drift predates the push by construction. That is a proof, not a heuristic —
# provided the path set is complete, which is why it is deliberately WIDER
# than the hook's own pre-commit `files:` trigger. Attribution must never
# clear a pusher it is unsure about.
#
# The asymmetry is the safety property: a too-wide path set can only fail to
# clear an innocent pusher (they see today's message, no worse), while a
# too-narrow one would clear a guilty one and lose the signal the hook exists
# for. Widen freely; never narrow to make a case pass.

# Every path whose content can change the exported JSON Schemas. Wider than
# `files:` in .pre-commit-config.yaml on purpose (see above): a schemars type
# can reference a struct in any module, so the whole crate source is in scope,
# as are the manifests and lockfile that pin schemars/serde themselves.
#
# The list is derived from what actually produces the artifact, not from what
# has produced a diff so far: `schemas.json` comes from ONE command,
# `cargo run --bin export_schemas --release` (src-tauri/scripts/generate_types.sh),
# so the inputs are the whole compiled crate graph plus everything that pins how
# it compiles. That is why the IN-REPO path dependencies and the toolchain pin
# are here even though nothing under them derives `JsonSchema` today — the day
# one does, or the day a feature edit in one of their manifests changes feature
# unification for `serde`/`chrono`/`uuid`, a narrower list would start clearing
# guilty pushers with nothing to notice. Out-of-repo inputs (the qontinui-schemas
# path deps, its TS compile step) are deliberately absent: a push to THIS repo
# cannot change them, so they can never be this push's fault.

# The base-ref cascade this library measures "before this push" against lives
# in a NEUTRAL sibling: `lib/push-range.sh`. It was moved out because the cargo
# pre-push gate needs the same cascade and has nothing to do with codegen
# attribution. Sourced rather than duplicated — one implementation, two
# opposite fallback policies (see that file's header).
#
# Guarded rather than sourced bare: under `set -e` a missing library aborts
# with a raw bash "No such file or directory", and every caller of this file is
# a hook that promises a typed message instead.
GEN_EVENTS_ATTRIBUTION_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ ! -f "$GEN_EVENTS_ATTRIBUTION_LIB_DIR/push-range.sh" ]; then
    echo "[gen-events-drift] ERROR: missing $GEN_EVENTS_ATTRIBUTION_LIB_DIR/push-range.sh" >&2
    echo "[gen-events-drift] It ships with this repo and carries the base-ref cascade" >&2
    echo "[gen-events-drift] attribution measures this push against. Restore it." >&2
    return 1 2>/dev/null || exit 1
fi
# shellcheck source=push-range.sh
. "$GEN_EVENTS_ATTRIBUTION_LIB_DIR/push-range.sh"

# Drop the git environment a HOOK inherits, so `git -C <dir>` actually means
# that directory.
#
# This is a correctness precondition, not hygiene. Git exports `GIT_DIR` (and
# friends) to every hook it runs, and those variables OVERRIDE `-C`: with
# `GIT_DIR` set, `git -C /some/other/repo log` reports the repo `GIT_DIR` names.
# Verified directly — two throwaway repos, `GIT_DIR=decoy git -C real log`
# prints decoy's commit.
#
# Two consequences, both observed live on 2026-08-24 the first time this
# library ran from a real pre-push hook:
#
#  - the attribution test's throwaway fixtures committed into the REAL
#    repository. Its `git -C "$WORK" commit` moved the branch being pushed to a
#    fixture commit and left the index holding five fixture files. (Recovered
#    from the reflog; nothing reached origin, because the resulting push
#    failed.)
#  - `gen-events-drift.sh`'s `git -C "$SCHEMAS_DIR" status` read THIS repo
#    rather than qontinui-schemas, so the shared-checkout dirty note described
#    the wrong repository.
#
# It was invisible until now only because nothing ever ran either script from a
# hook — the test said "run me by hand" and the drift guard's own git calls
# happen to name the repo whose hook is running. Both callers clear the
# environment before their first `git`.
gen_events_clear_inherited_git_env() {
    unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
        GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR GIT_PREFIX \
        GIT_INTERNAL_SUPER_PREFIX GIT_CONFIG GIT_CONFIG_COUNT \
        GIT_CONFIG_GLOBAL GIT_CONFIG_SYSTEM GIT_NAMESPACE \
        GIT_INDEX_VERSION GIT_QUARANTINE_PATH GIT_PUSH_CERT \
        GIT_REFLOG_ACTION
}

GEN_EVENTS_ATTRIBUTION_PATHS=(
    "src-tauri/src"
    "src-tauri/build.rs"
    "src-tauri/Cargo.toml"
    "src-tauri/scripts/generate_types.sh"
    # In-repo path dependencies of the crate `export_schemas` links into
    # (`qontinui-db = { path = "./clorinde" }`,
    #  `qontinui-spec-check = { path = "../crates/spec-check" }`).
    "src-tauri/clorinde"
    "crates/spec-check"
    "Cargo.toml"
    "Cargo.lock"
    # The compiler that expands the `schemars` derive. A channel bump is a real
    # input to the generated JSON and touches none of the paths above.
    "rust-toolchain.toml"
)

# Decide attribution for the repo at $1. Sets, in the caller's shell:
#
#   ATTRIBUTION_STATE   mine | pre-existing | unavailable
#   ATTRIBUTION_BASE_REF / ATTRIBUTION_BASE_SHA   what "before this push" meant
#   ATTRIBUTION_TOUCHED newline-separated codegen inputs this push touches
#   ATTRIBUTION_UNAVAILABLE_REASON  set only for `unavailable`
#
# `unavailable` is a distinct state, never folded into either verdict: a
# shallow clone or a remote-less checkout cannot answer the question, and
# guessing "pre-existing" there would silently downgrade a real failure. The
# caller fails closed on it.
gen_events_attribution() {
    local repo="$1"
    ATTRIBUTION_STATE="unavailable"
    ATTRIBUTION_BASE_REF=""
    ATTRIBUTION_BASE_SHA=""
    ATTRIBUTION_TOUCHED=""
    ATTRIBUTION_UNAVAILABLE_REASON=""

    if ! git -C "$repo" rev-parse --verify --quiet HEAD >/dev/null 2>&1; then
        ATTRIBUTION_UNAVAILABLE_REASON="no HEAD commit in $repo"
        return 0
    fi
    if [ "$(git -C "$repo" rev-parse --is-shallow-repository 2>/dev/null || echo true)" = "true" ]; then
        ATTRIBUTION_UNAVAILABLE_REASON="this is a shallow clone, so the merge-base with the upstream branch is not knowable"
        return 0
    fi

    local ref
    if ! ref="$(push_base_ref "$repo")"; then
        ATTRIBUTION_UNAVAILABLE_REASON="no upstream branch, origin/HEAD or origin/main to measure this push against"
        return 0
    fi
    ATTRIBUTION_BASE_REF="$ref"
    ATTRIBUTION_BASE_SHA="$(git -C "$repo" merge-base HEAD "$ref" 2>/dev/null || true)"
    if [ -z "$ATTRIBUTION_BASE_SHA" ]; then
        ATTRIBUTION_UNAVAILABLE_REASON="could not compute merge-base(HEAD, $ref)"
        return 0
    fi

    # Three sources, because a push carries all three: commits already made,
    # anything staged or unstaged (this hook also runs at pre-commit), and
    # brand-new untracked sources that a `git diff` cannot see.
    ATTRIBUTION_TOUCHED="$(
        {
            git -C "$repo" diff --name-only "$ATTRIBUTION_BASE_SHA" HEAD \
                -- "${GEN_EVENTS_ATTRIBUTION_PATHS[@]}" 2>/dev/null || true
            git -C "$repo" diff --name-only HEAD \
                -- "${GEN_EVENTS_ATTRIBUTION_PATHS[@]}" 2>/dev/null || true
            git -C "$repo" ls-files --others --exclude-standard \
                -- "${GEN_EVENTS_ATTRIBUTION_PATHS[@]}" 2>/dev/null || true
        } | sort -u | sed '/^$/d'
    )"

    if [ -n "$ATTRIBUTION_TOUCHED" ]; then
        ATTRIBUTION_STATE="mine"
    else
        ATTRIBUTION_STATE="pre-existing"
    fi
    return 0
}
