#!/usr/bin/env bash
#
# gen-events-attribution.sh — "is this drift THIS push's fault?"
#
# Sourced by `.pre-commit-hooks/gen-events-drift.sh`. Split into its own file
# so the decision can be tested against throwaway git repos without a Rust
# toolchain, a schemas checkout or a ~minute release build —
# `gen-events-drift-attribution-test.sh` does exactly that.
#
# THE PROBLEM THIS SOLVES
#
# The drift hook compares freshly generated bindings against
# `qontinui-schemas/ts/src/generated/`. That baseline is a BUILD ARTIFACT in a
# shared checkout, not a committed contract: it is regenerated by hand, rarely,
# by whoever last needed it. So it lags this repo's Rust by however many
# schema-touching commits have landed since. Every pusher after that point
# generates fresh bindings, diffs them against the lagging artifact, and is
# told "Your Rust changes would move ts/src/generated" — about a change they
# did not make.
#
# The drift is REAL. The blame is not. This is a false-attribution bug, not a
# false-detection one, and it is fixed by splitting the verdict rather than by
# weakening the check.
#
# It bites hardest at pre-push, where pre-commit computes the changed-file set
# over the whole pushed RANGE. On a long-lived or rebased branch that range is
# old-base..main, so a PEER's schema commit is what fires the hook while the
# pusher's own diff is (say) frontend-only.
#
# THE PREDICATE
#
# Compare the push's own commits — `merge-base(HEAD, upstream)..HEAD` — plus
# its uncommitted working tree, against the set of paths in THIS repo whose
# content can move `schemas.json`. If NONE of them is touched, then the very
# inputs that produced this diff are already on the upstream branch, so the
# drift predates the push by construction. That is a proof, not a heuristic —
# provided the path set is complete, which is why it is deliberately WIDER
# than the hook's own pre-commit `files:` trigger. Attribution must never
# clear a pusher it is unsure about.
#
# The asymmetry is the safety property: a too-wide path set can only fail to
# clear an innocent pusher (they see today's message, no worse), while a
# too-narrow one would clear a guilty one and lose the signal the hook exists
# for. Widen freely; never narrow to make a case pass.
#
# ONE DELIBERATE NARROWING, AND ITS GUARD
#
# Markdown is excluded (GEN_EVENTS_ATTRIBUTION_EXCLUDES below). That is a
# narrowing, made on evidence rather than to make a case pass: qontinui-runner
# #1667 pushed three `.md` files under src-tauri/src/fleet_commands/ and was
# blamed for the bindings, because `src-tauri/src` is a directory prefix and
# ~100 markdown files live under it. Markdown reaches the binary only as
# embedded data — `include_str!`/`include_bytes!` into consts, `include_dir!`
# into directory trees — none of which schemars reads.
#
# The narrowing is safe only while that stays true, so it is re-checked on
# EVERY attribution decision, against the working tree being attributed:
# `gen_events_markdown_premise_violations` below. If it finds a way markdown
# could reach `schemas.json`, or cannot run its probe at all, the decision
# drops the exclusion and attributes against the full list — the wider,
# never-clears-a-guilty-pusher direction — and says why in
# ATTRIBUTION_EXCLUDES_DROPPED_REASON. The attribution self-test runs the same
# function against the real tree, so a violation is also loud at test time.
#
# What the guard covers: text or directory embeds (`include_str!`,
# `include_bytes!`, `include_dir!`) beside `JsonSchema` or a `schemars(`
# attribute in the same file; a `#[doc = include_*!(..)]` attribute anywhere;
# a single-line `schemars(..)` attribute whose value is anything but a string
# or numeric literal (`description`, `title`, `example`, `default`,
# `extend("key" = EXPR)` — schemars 1 takes expressions for all of them); and
# a build script that names a markdown path at all.
#
# What it does NOT see, stated so nobody mistakes it for a proof:
#  - an embed in a file with neither `JsonSchema` nor `schemars(`, used by a
#    JsonSchema type in ANOTHER file through a rustfmt-wrapped attribute whose
#    value sits on its own line, or through a `macro_rules!` that builds the
#    attribute;
#  - a build script that reaches markdown through a path it assembles without
#    ever writing a `.md"` or `"md"` literal (a glob over a directory, say).
# It errs the other way on purpose elsewhere: a raw-string literal
# (`title = r"x"`) or a `true` value reads as a violation and merely costs the
# exclusion.

# Every path whose content can change the exported JSON Schemas. Wider than
# `files:` in .pre-commit-config.yaml on purpose (see above): a schemars type
# can reference a struct in any module, so the whole crate source is in scope,
# as are the manifests and lockfile that pin schemars/serde themselves.
#
# The list is derived from what actually produces the artifact, not from what
# has produced a diff so far: `schemas.json` comes from ONE command,
# `cargo run --bin export_schemas --release` (src-tauri/scripts/generate_types.sh),
# so the inputs are the whole compiled crate graph plus everything that pins how
# it compiles. That is why the IN-REPO path dependencies and the toolchain pin
# are here even though nothing under them derives `JsonSchema` today — the day
# one does, or the day a feature edit in one of their manifests changes feature
# unification for `serde`/`chrono`/`uuid`, a narrower list would start clearing
# guilty pushers with nothing to notice. Out-of-repo inputs (the qontinui-schemas
# path deps, its TS compile step) are deliberately absent: a push to THIS repo
# cannot change them, so they can never be this push's fault.

# The base-ref cascade this library measures "before this push" against lives
# in a NEUTRAL sibling: `lib/push-range.sh`. It was moved out because the cargo
# pre-push gate needs the same cascade and has nothing to do with codegen
# attribution. Sourced rather than duplicated — one implementation, two
# opposite fallback policies (see that file's header).
#
# Guarded rather than sourced bare: under `set -e` a missing library aborts
# with a raw bash "No such file or directory", and every caller of this file is
# a hook that promises a typed message instead.
GEN_EVENTS_ATTRIBUTION_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ ! -f "$GEN_EVENTS_ATTRIBUTION_LIB_DIR/push-range.sh" ]; then
    echo "[gen-events-drift] ERROR: missing $GEN_EVENTS_ATTRIBUTION_LIB_DIR/push-range.sh" >&2
    echo "[gen-events-drift] It ships with this repo and carries the base-ref cascade" >&2
    echo "[gen-events-drift] attribution measures this push against. Restore it." >&2
    return 1 2>/dev/null || exit 1
fi
# shellcheck source=push-range.sh
. "$GEN_EVENTS_ATTRIBUTION_LIB_DIR/push-range.sh"

# Drop the git environment a HOOK inherits, so `git -C <dir>` actually means
# that directory.
#
# This is a correctness precondition, not hygiene. Git exports `GIT_DIR` (and
# friends) to every hook it runs, and those variables OVERRIDE `-C`: with
# `GIT_DIR` set, `git -C /some/other/repo log` reports the repo `GIT_DIR` names.
# Verified directly — two throwaway repos, `GIT_DIR=decoy git -C real log`
# prints decoy's commit.
#
# Two consequences, both observed live on 2026-08-24 the first time this
# library ran from a real pre-push hook:
#
#  - the attribution test's throwaway fixtures committed into the REAL
#    repository. Its `git -C "$WORK" commit` moved the branch being pushed to a
#    fixture commit and left the index holding five fixture files. (Recovered
#    from the reflog; nothing reached origin, because the resulting push
#    failed.)
#  - `gen-events-drift.sh`'s `git -C "$SCHEMAS_DIR" status` read THIS repo
#    rather than qontinui-schemas, so the shared-checkout dirty note described
#    the wrong repository.
#
# It was invisible until now only because nothing ever ran either script from a
# hook — the test said "run me by hand" and the drift guard's own git calls
# happen to name the repo whose hook is running. Both callers clear the
# environment before their first `git`.
gen_events_clear_inherited_git_env() {
    unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
        GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR GIT_PREFIX \
        GIT_INTERNAL_SUPER_PREFIX GIT_CONFIG GIT_CONFIG_COUNT \
        GIT_CONFIG_GLOBAL GIT_CONFIG_SYSTEM GIT_NAMESPACE \
        GIT_INDEX_VERSION GIT_QUARANTINE_PATH GIT_PUSH_CERT \
        GIT_REFLOG_ACTION
}

GEN_EVENTS_ATTRIBUTION_PATHS=(
    "src-tauri/src"
    "src-tauri/build.rs"
    "src-tauri/Cargo.toml"
    "src-tauri/scripts/generate_types.sh"
    # In-repo path dependencies of the crate `export_schemas` links into
    # (`qontinui-db = { path = "./clorinde" }`,
    #  `qontinui-spec-check = { path = "../crates/spec-check" }`).
    "src-tauri/clorinde"
    "crates/spec-check"
    "Cargo.toml"
    "Cargo.lock"
    # The compiler that expands the `schemars` derive. A channel bump is a real
    # input to the generated JSON and touches none of the paths above.
    "rust-toolchain.toml"
)

# Appended to every pathspec above. Non-glob pathspec magic lets `*` cross `/`,
# so this one entry reaches every depth under every directory-prefix input.
# The whole case for it — and the premise guard that keeps it honest — is in
# the header's "ONE DELIBERATE NARROWING". Nothing else belongs here without a
# guard of its own.
GEN_EVENTS_ATTRIBUTION_EXCLUDES=(
    ':(exclude)*.md'
)

# Where the premise guard looks: the directory-prefix inputs above, the only
# ones under which a `.md` could be a sibling of Rust that embeds it.
GEN_EVENTS_PREMISE_PATHS=(
    "src-tauri/src"
    "src-tauri/clorinde"
    "crates/spec-check"
)

# Build scripts the export build runs. A build script can read a markdown file
# and GENERATE a JsonSchema type or doc from it, which no embed arm would see.
GEN_EVENTS_PREMISE_BUILD_SCRIPTS=(
    "src-tauri/build.rs"
    ":(glob)src-tauri/src/**/build.rs"
    ":(glob)src-tauri/clorinde/**/build.rs"
    ":(glob)crates/spec-check/**/build.rs"
)

# `git grep` in the WORKING TREE of $1, untracked files included — the
# regeneration compiles the working tree, so that is what the premise is about.
# $2 names how many pathspecs follow; the rest are grep arguments. Prints
# matches; exit 1 from git grep is "no match" and is success here. Anything
# above 1 is a broken probe: printed as an `ERROR` line and returned as 2, so a
# caller can never read a failed query as a clean tree.
_gen_events_grep_in() {
    local dir="$1" n="$2"; shift 2
    local paths=("${@:1:$n}"); shift "$n"
    local out rc=0
    out="$(git -C "$dir" grep --untracked "$@" -- "${paths[@]}" 2>&1)" || rc=$?
    if [ "$rc" -gt 1 ]; then
        printf 'ERROR git grep %s (exit %d): %s\n' "$*" "$rc" "${out%%$'\n'*}"
        return 2
    fi
    [ "$rc" -eq 0 ] && printf '%s\n' "$out"
    return 0
}

# The same over the premise paths — what every embed arm reads.
gen_events_premise_grep() {
    local dir="$1"; shift
    _gen_events_grep_in "$dir" "${#GEN_EVENTS_PREMISE_PATHS[@]}" "${GEN_EVENTS_PREMISE_PATHS[@]}" "$@"
}

# Could markdown in the repo at $1 reach `schemas.json`? Prints one line per
# way it could. Exit 0: premise holds. Exit 1: violated. Exit 2: the probe
# itself failed (its ERROR lines are printed too) — which a caller must treat
# exactly like a violation.
#
# File-level arms deliberately over-approximate — co-occurrence in one file,
# not proof of a data path — because a false alarm only costs a wider list,
# while a miss clears a guilty pusher.
gen_events_markdown_premise_violations() {
    local dir="$1" probe_failed=0 found=0
    local inc_text md_lit schema inc_dir schemars_attr inc_any line
    inc_text="$(gen_events_premise_grep "$dir" -l -E 'include_(str|bytes)!' | LC_ALL=C sort)" || probe_failed=1
    md_lit="$(gen_events_premise_grep "$dir" -l -E '\.md"' | LC_ALL=C sort)" || probe_failed=1
    schema="$(gen_events_premise_grep "$dir" -l -F 'JsonSchema' | LC_ALL=C sort)" || probe_failed=1
    inc_dir="$(gen_events_premise_grep "$dir" -l -F 'include_dir!' | LC_ALL=C sort)" || probe_failed=1
    schemars_attr="$(gen_events_premise_grep "$dir" -l -F 'schemars(' | LC_ALL=C sort)" || probe_failed=1
    inc_any="$(printf '%s\n' "$inc_text" "$inc_dir" | sed '/^$/d' | LC_ALL=C sort -u)"
    # A failed probe prints its ERROR line into whichever list it fed, and
    # `sort` returns 0 over it — so the lists are scanned, not just the flags.
    if printf '%s\n' "$inc_text" "$md_lit" "$schema" "$inc_dir" "$schemars_attr" | grep -q '^ERROR'; then
        printf '%s\n' "$inc_text" "$md_lit" "$schema" "$inc_dir" "$schemars_attr" | grep '^ERROR'
        probe_failed=1
    fi

    # `comm` over sorted lists rather than a `for f in $list` loop, which would
    # word-split a path containing a space.
    _premise_both() { LC_ALL=C comm -12 <(printf '%s\n' "$1" | sed '/^$/d') <(printf '%s\n' "$2" | sed '/^$/d'); }

    # Arm 1: text-embeds something, names a `.md"` literal, mentions JsonSchema.
    # Wider than `include_str!("x.md")` on one line, so it also covers
    # `concat!`/multi-line forms.
    while IFS= read -r line; do
        [ -n "$line" ] || continue
        printf '%s: include_str!/include_bytes! of markdown in a file that mentions JsonSchema\n' "$line"
        found=1
    done < <(_premise_both "$(_premise_both "$inc_text" "$md_lit")" "$schema")
    # Arm 2: `include_dir!` embeds whole trees (fleet_skills.rs, fleet_agents.rs
    # ship markdown this way) and never names a `.md` literal, so any use of it
    # beside JsonSchema is a violation on its own.
    while IFS= read -r line; do
        [ -n "$line" ] || continue
        printf '%s: include_dir! in a file that mentions JsonSchema\n' "$line"
        found=1
    done < <(_premise_both "$inc_dir" "$schema")
    # Arm 3: any embed in a file that carries a schemars attribute. File-level,
    # so a rustfmt-wrapped `#[schemars(description = include_str!(..))]` is
    # caught though no single line holds both halves.
    while IFS= read -r line; do
        [ -n "$line" ] || continue
        printf '%s: include_*! in a file with a schemars( attribute\n' "$line"
        found=1
    done < <(_premise_both "$inc_any" "$schemars_attr")
    unset -f _premise_both
    # Arm 4: a doc attribute fed from a file becomes the schema's `description`.
    # Anchored to attribute syntax so `let doc = include_str!(..)` is not one.
    line="$(gen_events_premise_grep "$dir" -n -E '(\[|,|\()[[:space:]]*doc[[:space:]]*=[[:space:]]*include_(str|bytes)!')" || probe_failed=1
    if [ -n "$line" ]; then printf '%s\n' "$line"; found=1; fi
    # Arm 5: schemars 1 takes EXPRESSIONS for description, title, example,
    # default and `extend("key" = EXPR)`, so any `=` in a schemars attribute
    # whose value is not a string or numeric literal may be an embedded const
    # from another file. `[^=!<>]=` so `==`/`!=`/`<=` in an expression are not
    # read as the assignment; `extend("key" = ..)` matches through the `" =`.
    line="$(gen_events_premise_grep "$dir" -n -E 'schemars\(.*[^=!<>]=[[:space:]]*[^"[:space:][:digit:]-]')" || probe_failed=1
    if [ -n "$line" ]; then printf '%s\n' "$line"; found=1; fi
    # Arm 6: a build script that names a markdown path at all — a `.md"`
    # literal or an `"md"` extension check. Deliberately not "a read call on a
    # .md path": build.rs mentions `tokio-console.md` in a message string, and
    # a read through a const path would slip a read-call pattern anyway.
    line="$(_gen_events_grep_in "$dir" "${#GEN_EVENTS_PREMISE_BUILD_SCRIPTS[@]}" \
        "${GEN_EVENTS_PREMISE_BUILD_SCRIPTS[@]}" -n -E '\.md"|"md"')" || probe_failed=1
    if [ -n "$line" ]; then
        printf '%s\n' "$line" | sed 's/$/  (a build script naming markdown)/'
        found=1
    fi

    [ "$probe_failed" = "1" ] && return 2
    [ "$found" = "1" ] && return 1
    return 0
}

# Read NUL-delimited records from stdin into the global array _GEA_RECS. The
# producer appends its own exit status as one final `rc=N` record, because a
# process substitution's status is otherwise lost; anything but `rc=0` last —
# including a truncated stream whose final path swallowed the sentinel — is
# a failure. Global rather than a nameref so it runs on bash older than 4.3.
_gen_events_read_z() {
    _GEA_RECS=()
    local rec recs=() n
    while IFS= read -r -d '' rec; do recs+=("$rec"); done
    n="${#recs[@]}"
    [ "$n" -gt 0 ] && [ "${recs[$((n - 1))]}" = "rc=0" ] || return 1
    [ "$n" -gt 1 ] && _GEA_RECS=("${recs[@]:0:$((n - 1))}")
    return 0
}

# Decide attribution for the repo at $1. Sets, in the caller's shell:
#
#   ATTRIBUTION_STATE   mine | pre-existing | unavailable
#   ATTRIBUTION_BASE_REF / ATTRIBUTION_BASE_SHA   what "before this push" meant
#   ATTRIBUTION_TOUCHED newline-separated codegen inputs this push touches
#   ATTRIBUTION_TOUCHED_DETAIL  the same paths as `<path><TAB><source>` lines,
#                       source one of `committed` (in merge-base..HEAD),
#                       `uncommitted` (staged or unstaged, `git diff HEAD`) or
#                       `untracked`. A path in several sources gets one line
#                       per source — see the computation for why. A path
#                       holding a tab or newline appears shell-escaped, with a
#                       third field `escaped`. Paths are raw, never C-quoted.
#   ATTRIBUTION_EXCLUDES_DROPPED_REASON  "" when the markdown exclusion
#                       applied; otherwise why this decision ran on the full,
#                       unexcluded list (premise violated, or its probe failed)
#   ATTRIBUTION_UNAVAILABLE_REASON  set only for `unavailable` — including a
#                       git call that failed, which must never read as "touched
#                       nothing" and clear the pusher
#
# `unavailable` is a distinct state, never folded into either verdict: a
# shallow clone or a remote-less checkout cannot answer the question, and
# guessing "pre-existing" there would silently downgrade a real failure. The
# caller fails closed on it.
gen_events_attribution() {
    local repo="$1"
    ATTRIBUTION_STATE="unavailable"
    ATTRIBUTION_BASE_REF=""
    ATTRIBUTION_BASE_SHA=""
    ATTRIBUTION_TOUCHED=""
    ATTRIBUTION_TOUCHED_DETAIL=""
    ATTRIBUTION_EXCLUDES_DROPPED_REASON=""
    ATTRIBUTION_UNAVAILABLE_REASON=""

    if ! git -C "$repo" rev-parse --verify --quiet HEAD >/dev/null 2>&1; then
        ATTRIBUTION_UNAVAILABLE_REASON="no HEAD commit in $repo"
        return 0
    fi
    if [ "$(git -C "$repo" rev-parse --is-shallow-repository 2>/dev/null || echo true)" = "true" ]; then
        ATTRIBUTION_UNAVAILABLE_REASON="this is a shallow clone, so the merge-base with the upstream branch is not knowable"
        return 0
    fi

    local ref
    if ! ref="$(push_base_ref "$repo")"; then
        ATTRIBUTION_UNAVAILABLE_REASON="no upstream branch, origin/HEAD or origin/main to measure this push against"
        return 0
    fi
    ATTRIBUTION_BASE_REF="$ref"
    ATTRIBUTION_BASE_SHA="$(git -C "$repo" merge-base HEAD "$ref" 2>/dev/null || true)"
    if [ -z "$ATTRIBUTION_BASE_SHA" ]; then
        ATTRIBUTION_UNAVAILABLE_REASON="could not compute merge-base(HEAD, $ref)"
        return 0
    fi

    # Three sources, because a push carries all three: commits already made,
    # anything staged or unstaged (this hook also runs at pre-commit), and
    # brand-new untracked sources that a `git diff` cannot see.
    #
    # Kept apart rather than merged at once, because they are not equally the
    # push's. Only `committed` is IN the push; the other two are the pusher's
    # working tree, which the regeneration reads — so they still make the
    # verdict `mine` — but which the author may not realise is involved (#1667
    # was blamed for a dirty Cargo.lock it never pushed). The detail says which.
    # The markdown exclusion applies only while its premise holds for the tree
    # being attributed. `&& rc=0 || rc=$?` rather than a bare assignment: the
    # hook runs under `set -e`, and a non-zero here is an answer, not a crash.
    local premise premise_rc
    premise="$(gen_events_markdown_premise_violations "$repo")" && premise_rc=0 || premise_rc=$?
    local pathspec=("${GEN_EVENTS_ATTRIBUTION_PATHS[@]}")
    if [ "$premise_rc" -eq 0 ]; then
        pathspec+=("${GEN_EVENTS_ATTRIBUTION_EXCLUDES[@]}")
    elif [ "$premise_rc" -eq 1 ]; then
        ATTRIBUTION_EXCLUDES_DROPPED_REASON="markdown may reach schemas.json (${premise%%$'\n'*})"
    else
        ATTRIBUTION_EXCLUDES_DROPPED_REASON="the markdown premise probe failed (${premise%%$'\n'*})"
    fi

    # Each call's status is checked, not swallowed: an empty list from a git
    # that FAILED would read as "touched nothing" and clear the pusher — the
    # one direction this library must never err in.
    #
    # `-z` throughout. Without it git C-quotes any path with non-ASCII, `"`,
    # `\` or a control character (`"src-tauri/src/\303\251 b.rs"`), and the
    # labels and the set-aside command then name a file that does not exist.
    local touched_lines="" detail_lines="" src
    for src in committed uncommitted untracked; do
        case "$src" in
            committed)
                _gen_events_read_z < <(git -C "$repo" diff --name-only -z "$ATTRIBUTION_BASE_SHA" HEAD \
                    -- "${pathspec[@]}" 2>/dev/null; printf 'rc=%d\0' "$?") \
                || { ATTRIBUTION_UNAVAILABLE_REASON="git diff $ATTRIBUTION_BASE_SHA HEAD failed, so this push's commits could not be read"; return 0; } ;;
            uncommitted)
                _gen_events_read_z < <(git -C "$repo" diff --name-only -z HEAD \
                    -- "${pathspec[@]}" 2>/dev/null; printf 'rc=%d\0' "$?") \
                || { ATTRIBUTION_UNAVAILABLE_REASON="git diff HEAD failed, so the working tree could not be read"; return 0; } ;;
            untracked)
                _gen_events_read_z < <(git -C "$repo" ls-files --others --exclude-standard -z \
                    -- "${pathspec[@]}" 2>/dev/null; printf 'rc=%d\0' "$?") \
                || { ATTRIBUTION_UNAVAILABLE_REASON="git ls-files --others failed, so untracked sources could not be read"; return 0; } ;;
        esac
        # A path containing a tab or newline cannot sit in a line-and-tab
        # format, so it is carried shell-escaped (printf %q, which emits no
        # raw tab or newline) with a third `escaped` field. It still counts:
        # dropping it would clear a pusher over a file name.
        local p shown
        for p in ${_GEA_RECS[@]+"${_GEA_RECS[@]}"}; do
            case "$p" in
                *$'\t'*|*$'\n'*)
                    shown="$(printf '%q' "$p")"
                    detail_lines+="$shown"$'\t'"$src"$'\t'"escaped"$'\n' ;;
                *)
                    shown="$p"
                    detail_lines+="$p"$'\t'"$src"$'\n' ;;
            esac
            touched_lines+="$shown"$'\n'
        done
    done

    ATTRIBUTION_TOUCHED="$(printf '%s' "$touched_lines" | sort -u | sed '/^$/d')"

    # One line per (path, source), not one per path with a precedence rule.
    # A path both committed AND dirty is two facts the reader needs: it is in
    # the push, and the working tree the regen read differs from what is being
    # pushed. Collapsing to `committed` would hide the second. LC_ALL=C so TAB
    # sorts below every path character and a path's lines stay adjacent.
    ATTRIBUTION_TOUCHED_DETAIL="$(printf '%s' "$detail_lines" | LC_ALL=C sort -u | sed '/^$/d')"

    if [ -n "$ATTRIBUTION_TOUCHED" ]; then
        ATTRIBUTION_STATE="mine"
    else
        ATTRIBUTION_STATE="pre-existing"
    fi
    return 0
}

# The MINE arm's explanation, on stdout, one line per message line, for the
# hook to prefix and send to stderr. Lives here rather than in the hook so the
# self-test can pin it: which lead line, which labels, and that the set-aside
# advice is a command that actually runs. Reads the ATTRIBUTION_* variables a
# `mine` decision set.
gen_events_render_mine() {
    local p src flag label has_committed=0 escaped_seen=0
    local not_pushed=()
    while IFS=$'\t' read -r p src flag; do
        [ -n "$p" ] || continue
        [ "$src" = "committed" ] && has_committed=1
    done <<< "$ATTRIBUTION_TOUCHED_DETAIL"

    # "This push" is only true of committed entries. With none, the drift is
    # still the pusher's to look at — the regen read their working tree — but
    # saying their PUSH changed the inputs would be the false claim #1667 met.
    if [ "$has_committed" = "1" ]; then
        echo "This push changes sources that feed them, so the diff below is yours."
    else
        echo "Your working tree (not this push's commits) changes sources that feed them,"
        echo "so the diff below is yours to check."
    fi
    echo "Measured against $ATTRIBUTION_BASE_REF (merge-base ${ATTRIBUTION_BASE_SHA:0:12}); the files are:"
    while IFS=$'\t' read -r p src flag; do
        [ -n "$p" ] || continue
        case "$src" in
            committed)   label="committed in this push" ;;
            uncommitted) label="uncommitted changes — not part of this push" ;;
            untracked)   label="untracked — not part of this push" ;;
            *)           label="source unknown: '$src'" ;;
        esac
        [ "$flag" = "escaped" ] && { label+="; name shell-escaped"; escaped_seen=1; }
        # The stash word, built here while the escaped flag is in hand. `:/`
        # (top-level pathspec magic) so it works from any subdirectory; %q so
        # a space, quote or non-ASCII byte survives the shell. An escaped path
        # is already a shell word — `:/` concatenates onto it unquoted.
        if [ "$src" != "committed" ]; then
            if [ "$flag" = "escaped" ]; then not_pushed+=(":/$p"); else not_pushed+=("$(printf '%q' ":/$p")"); fi
        fi
        echo "    $p  ($label)"
    done <<< "$ATTRIBUTION_TOUCHED_DETAIL"
    if [ "$escaped_seen" = "1" ]; then
        echo "(A name marked shell-escaped contains a tab or newline and is shown as \$'...'.)"
    fi

    if [ -n "$ATTRIBUTION_EXCLUDES_DROPPED_REASON" ]; then
        echo "Markdown was counted as a codegen input this time: $ATTRIBUTION_EXCLUDES_DROPPED_REASON."
    fi

    # The set-aside advice. Not plain `git stash` (misses untracked files) and
    # not `git checkout -- <path>` (fails on untracked, destroys tracked work).
    # And never `git stash pop` or a positional stash@{n} remembered from
    # earlier: the stash stack is shared by every worktree of the repo and
    # other sessions push to it, so the entry is found by its unique message.
    if [ "${#not_pushed[@]}" -gt 0 ]; then
        local tag
        tag="gen-events-drift-$(date +%Y%m%d%H%M%S)-$$"
        echo "Entries marked 'not part of this push' come from your working tree, which the"
        echo "regeneration reads. To see whether the drift is yours, set them aside and"
        echo "re-run — with a temporary WIP commit, or a stash entry found BY ITS TAG:"
        echo "    git stash push --include-untracked -m \"$tag\" -- ${not_pushed[*]}"
        echo "    git stash list --format='%H %gs' | grep $tag    # note that sha"
        echo "  then re-run the push, and restore:"
        echo "    git stash apply --index <that sha>"
        echo "    git stash list --format='%gd %gs' | grep $tag   # its CURRENT stash@{n}"
        echo "    git stash drop 'stash@{n}'"
        echo "  Never \`git stash pop\`: the stack is shared, and a pop can take another session's entry."
    fi
    echo "Part of the diff may still be pre-existing — the baseline is a build"
    echo "artifact in a shared checkout and may have been behind before you began."
}
