#!/usr/bin/env bash
#
# gen-events-attribution.sh — "is this drift THIS push's fault?"
#
# Sourced by `.pre-commit-hooks/gen-events-drift.sh`. Split into its own file
# so the decision can be tested against throwaway git repos without a Rust
# toolchain, a schemas checkout or a ~minute release build —
# `gen-events-drift-attribution-test.sh` does exactly that.
#
# THE PROBLEM THIS SOLVES
#
# The drift hook compares freshly generated bindings against
# `qontinui-schemas/ts/src/generated/`. That baseline is a BUILD ARTIFACT in a
# shared checkout, not a committed contract: it is regenerated by hand, rarely,
# by whoever last needed it. So it lags this repo's Rust by however many
# schema-touching commits have landed since. Every pusher after that point
# generates fresh bindings, diffs them against the lagging artifact, and is
# told "Your Rust changes would move ts/src/generated" — about a change they
# did not make.
#
# The drift is REAL. The blame is not. This is a false-attribution bug, not a
# false-detection one, and it is fixed by splitting the verdict rather than by
# weakening the check.
#
# It bites hardest at pre-push, where pre-commit computes the changed-file set
# over the whole pushed RANGE. On a long-lived or rebased branch that range is
# old-base..main, so a PEER's schema commit is what fires the hook while the
# pusher's own diff is (say) frontend-only.
#
# THE PREDICATE
#
# Compare the push's own commits — `merge-base(HEAD, upstream)..HEAD` — plus
# its uncommitted working tree, against the set of paths in THIS repo whose
# content can move `schemas.json`. If NONE of them is touched, then the very
# inputs that produced this diff are already on the upstream branch, so the
# drift predates the push by construction. That is a proof, not a heuristic —
# provided the path set is complete, which is why it is deliberately WIDER
# than the hook's own pre-commit `files:` trigger. Attribution must never
# clear a pusher it is unsure about.
#
# The asymmetry is the safety property: a too-wide path set can only fail to
# clear an innocent pusher (they see today's message, no worse), while a
# too-narrow one would clear a guilty one and lose the signal the hook exists
# for. Widen freely; never narrow to make a case pass.

# Every path whose content can change the exported JSON Schemas. Wider than
# `files:` in .pre-commit-config.yaml on purpose (see above): a schemars type
# can reference a struct in any module, so the whole crate source is in scope,
# as are the manifests and lockfile that pin schemars/serde themselves.
GEN_EVENTS_ATTRIBUTION_PATHS=(
    "src-tauri/src"
    "src-tauri/build.rs"
    "src-tauri/Cargo.toml"
    "src-tauri/scripts/generate_types.sh"
    "Cargo.toml"
    "Cargo.lock"
)

# Resolve the ref this push is measured against: the branch's own upstream
# first (so "my commits" means the ones not yet pushed), then the remote's
# default branch, then origin/main. Prints the ref name, or nothing.
gen_events_attribution_base_ref() {
    local repo="$1" ref
    for ref in \
        "$(git -C "$repo" rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null || true)" \
        "$(git -C "$repo" symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null || true)" \
        "origin/main"
    do
        [ -n "$ref" ] || continue
        git -C "$repo" rev-parse --verify --quiet "${ref}^{commit}" >/dev/null 2>&1 || continue
        git -C "$repo" merge-base HEAD "$ref" >/dev/null 2>&1 || continue
        printf '%s\n' "$ref"
        return 0
    done
    return 1
}

# Decide attribution for the repo at $1. Sets, in the caller's shell:
#
#   ATTRIBUTION_STATE   mine | pre-existing | unavailable
#   ATTRIBUTION_BASE_REF / ATTRIBUTION_BASE_SHA   what "before this push" meant
#   ATTRIBUTION_TOUCHED newline-separated codegen inputs this push touches
#   ATTRIBUTION_UNAVAILABLE_REASON  set only for `unavailable`
#
# `unavailable` is a distinct state, never folded into either verdict: a
# shallow clone or a remote-less checkout cannot answer the question, and
# guessing "pre-existing" there would silently downgrade a real failure. The
# caller fails closed on it.
gen_events_attribution() {
    local repo="$1"
    ATTRIBUTION_STATE="unavailable"
    ATTRIBUTION_BASE_REF=""
    ATTRIBUTION_BASE_SHA=""
    ATTRIBUTION_TOUCHED=""
    ATTRIBUTION_UNAVAILABLE_REASON=""

    if ! git -C "$repo" rev-parse --verify --quiet HEAD >/dev/null 2>&1; then
        ATTRIBUTION_UNAVAILABLE_REASON="no HEAD commit in $repo"
        return 0
    fi
    if [ "$(git -C "$repo" rev-parse --is-shallow-repository 2>/dev/null || echo true)" = "true" ]; then
        ATTRIBUTION_UNAVAILABLE_REASON="this is a shallow clone, so the merge-base with the upstream branch is not knowable"
        return 0
    fi

    local ref
    if ! ref="$(gen_events_attribution_base_ref "$repo")"; then
        ATTRIBUTION_UNAVAILABLE_REASON="no upstream branch, origin/HEAD or origin/main to measure this push against"
        return 0
    fi
    ATTRIBUTION_BASE_REF="$ref"
    ATTRIBUTION_BASE_SHA="$(git -C "$repo" merge-base HEAD "$ref" 2>/dev/null || true)"
    if [ -z "$ATTRIBUTION_BASE_SHA" ]; then
        ATTRIBUTION_UNAVAILABLE_REASON="could not compute merge-base(HEAD, $ref)"
        return 0
    fi

    # Three sources, because a push carries all three: commits already made,
    # anything staged or unstaged (this hook also runs at pre-commit), and
    # brand-new untracked sources that a `git diff` cannot see.
    ATTRIBUTION_TOUCHED="$(
        {
            git -C "$repo" diff --name-only "$ATTRIBUTION_BASE_SHA" HEAD \
                -- "${GEN_EVENTS_ATTRIBUTION_PATHS[@]}" 2>/dev/null || true
            git -C "$repo" diff --name-only HEAD \
                -- "${GEN_EVENTS_ATTRIBUTION_PATHS[@]}" 2>/dev/null || true
            git -C "$repo" ls-files --others --exclude-standard \
                -- "${GEN_EVENTS_ATTRIBUTION_PATHS[@]}" 2>/dev/null || true
        } | sort -u | sed '/^$/d'
    )"

    if [ -n "$ATTRIBUTION_TOUCHED" ]; then
        ATTRIBUTION_STATE="mine"
    else
        ATTRIBUTION_STATE="pre-existing"
    fi
    return 0
}
