//! State machine routes — states, state groups, and transitions.
//!
//! These endpoints proxy to the webview SDK's state machine model via IPC.
//! Each handler is generated by one of the `ipc_handler_*` macros defined in
//! `mod.rs` — the macros expand to a thin async handler that calls
//! `ui_bridge_request_sync` with a JSON payload and returns the SDK's
//! response as an `ApiResponse<Value>`.
//!
//! Route families covered:
//!   - `/control/states*`            — read-only state listings
//!   - `/control/state/{id}/*`       — single-state activate/deactivate
//!   - `/control/state-groups` + `/control/state-group/{id}/*`
//!   - `/control/transitions` + `/control/transition/{id}/*`

use std::sync::Arc;

use axum::{extract::State, http::StatusCode, response::Json};

use crate::mcp::types::{ApiResponse, ApiState};

use super::request::ui_bridge_request_sync;
use super::{ipc_handler_get, ipc_handler_path_get, ipc_handler_path_post, ipc_handler_post};

// Read-only listings
ipc_handler_get!(ui_bridge_get_states_handler, "get_states");
ipc_handler_get!(ui_bridge_get_active_states_handler, "get_active_states");
ipc_handler_get!(ui_bridge_get_state_snapshot_handler, "get_state_snapshot");
ipc_handler_get!(ui_bridge_get_state_groups_handler, "get_state_groups");
ipc_handler_get!(ui_bridge_get_transitions_handler, "get_transitions");

// Single-state
ipc_handler_path_get!(ui_bridge_get_state_handler, "get_state", "stateId");
ipc_handler_path_post!(
    ui_bridge_activate_state_handler,
    "activate_state",
    "stateId"
);
ipc_handler_path_post!(
    ui_bridge_deactivate_state_handler,
    "deactivate_state",
    "stateId"
);

// State groups
ipc_handler_path_post!(
    ui_bridge_activate_state_group_handler,
    "activate_state_group",
    "groupId"
);
ipc_handler_path_post!(
    ui_bridge_deactivate_state_group_handler,
    "deactivate_state_group",
    "groupId"
);

// Transitions
ipc_handler_path_get!(
    ui_bridge_can_execute_transition_handler,
    "can_execute_transition",
    "transitionId"
);
ipc_handler_path_post!(
    ui_bridge_execute_transition_handler,
    "execute_transition",
    "transitionId"
);

// Path-finding / multi-state navigation
ipc_handler_post!(ui_bridge_find_state_path_handler, "find_state_path");
ipc_handler_post!(ui_bridge_navigate_to_state_handler, "navigate_to_state");

pub fn routes() -> axum::Router<Arc<ApiState>> {
    use axum::routing::{get, post};
    axum::Router::new()
        .route(
            "/ui-bridge/control/states",
            get(ui_bridge_get_states_handler),
        )
        .route(
            "/ui-bridge/control/states/active",
            get(ui_bridge_get_active_states_handler),
        )
        .route(
            "/ui-bridge/control/states/snapshot",
            get(ui_bridge_get_state_snapshot_handler),
        )
        .route(
            "/ui-bridge/control/states/find-path",
            post(ui_bridge_find_state_path_handler),
        )
        .route(
            "/ui-bridge/control/states/navigate",
            post(ui_bridge_navigate_to_state_handler),
        )
        .route(
            "/ui-bridge/control/state/{id}",
            get(ui_bridge_get_state_handler),
        )
        .route(
            "/ui-bridge/control/state/{id}/activate",
            post(ui_bridge_activate_state_handler),
        )
        .route(
            "/ui-bridge/control/state/{id}/deactivate",
            post(ui_bridge_deactivate_state_handler),
        )
        .route(
            "/ui-bridge/control/state-groups",
            get(ui_bridge_get_state_groups_handler),
        )
        .route(
            "/ui-bridge/control/state-group/{id}/activate",
            post(ui_bridge_activate_state_group_handler),
        )
        .route(
            "/ui-bridge/control/state-group/{id}/deactivate",
            post(ui_bridge_deactivate_state_group_handler),
        )
        .route(
            "/ui-bridge/control/transitions",
            get(ui_bridge_get_transitions_handler),
        )
        .route(
            "/ui-bridge/control/transition/{id}/can-execute",
            get(ui_bridge_can_execute_transition_handler),
        )
        .route(
            "/ui-bridge/control/transition/{id}/execute",
            post(ui_bridge_execute_transition_handler),
        )
}

pub fn route_entries() -> &'static [(&'static str, &'static str)] {
    &[
        ("GET", "/ui-bridge/control/states"),
        ("GET", "/ui-bridge/control/states/active"),
        ("GET", "/ui-bridge/control/states/snapshot"),
        ("POST", "/ui-bridge/control/states/find-path"),
        ("POST", "/ui-bridge/control/states/navigate"),
        ("GET", "/ui-bridge/control/state/{id}"),
        ("POST", "/ui-bridge/control/state/{id}/activate"),
        ("POST", "/ui-bridge/control/state/{id}/deactivate"),
        ("GET", "/ui-bridge/control/state-groups"),
        ("POST", "/ui-bridge/control/state-group/{id}/activate"),
        ("POST", "/ui-bridge/control/state-group/{id}/deactivate"),
        ("GET", "/ui-bridge/control/transitions"),
        ("GET", "/ui-bridge/control/transition/{id}/can-execute"),
        ("POST", "/ui-bridge/control/transition/{id}/execute"),
    ]
}
