//! PR-shepherd Phase 5 — remediation-plan generation + last-resort vet-imp/fix
//! session spawn. Part of plan `2026-07-04-runner-pr-shepherd.md`.
//!
//! On a CONFIRMED coord defect (Phase 3 `ShepherdIntent::Escalate`) that a
//! reevaluate nudge did not clear, or a dead-author `orphaned-red` fallback
//! (Phase 4), this module:
//!
//! 1. Renders a coord-defect remediation plan into `D:/qontinui-root/plans/`
//!    ([`render_remediation_plan`] — PURE, unit-tested from recorded evidence).
//! 2. **Dedupes** before writing (Phase 5.4 coexistence): an OPEN plan for the
//!    same defect class already in `plans/` (covers the fleet-wide
//!    `merge-train-steward`, which authors into the same dir + runs the same
//!    `/vet-imp`), OR a `pr_shepherd_remediations` marker row younger than the
//!    cooldown, is a dedup hit → skip.
//! 3. Spawns a child `TaskRun` running `/vet-imp <plan>` (or a bounded
//!    diagnose/shepherd prompt for `orphaned-red` — the PR there is GREEN but
//!    unowned while coord is down) — but ONLY when `QONTINUI_PR_SHEPHERD_SPAWN`
//!    is on. With spawn off the plan + marker are still written; no session.
//!
//! The runner daemon is the LAST-RESORT rung beneath coord's own Unlandable
//! Shepherd and the merge-train-steward — the only rung that still fires when
//! coord is the broken component. Coexistence rung (i) — "coord's shepherd has
//! a live attempt for this (PR, head)" — is checked at the call site
//! (`watchers::pr_watcher`) via
//! [`super::coord_pr_merge_client::CoordPrMergeClient::unlandable_attempt_live`]
//! before this module is invoked.

use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::database::pg::PgDb;
use crate::trigger_system::watchers::pr_watcher::PrWatcherDeps;

/// The canonical plans directory (shared with the merge-train-steward).
const PLANS_DIR: &str = "D:/qontinui-root/plans";

/// The evidence bundle a remediation plan renders from. Every field is either a
/// coord-reported value (verdict/events/graph) or a runner witness, so
/// [`render_remediation_plan`] is a pure function of this struct.
#[derive(Debug, Clone)]
pub struct RemediationPlanContext {
    /// `YYYY-MM-DD` (from `chrono::Utc::now()` at the call site — never a
    /// workflow-script `Date::now`).
    pub date: String,
    /// The `CoordDefectClass` kebab id (e.g. `stale-ingest`).
    pub defect_class: String,
    /// The suspected coord code path hint for this class.
    pub suspected_coord_path: String,
    pub repo_full_name: String,
    pub pr_number: u64,
    pub head_sha: String,
    /// How long the PR has been green-but-unmerged (the streak).
    pub green_for_secs: u64,
    /// Verdict `outer_state` (coord's `OuterState`).
    pub outer_state: Option<String>,
    /// Verdict `block_reason` (coord's `BlockReason::code`).
    pub block_reason: Option<String>,
    /// Verdict `next_action` prose.
    pub next_action: String,
    /// The newest `predicate_eval` `detail` evidence blob (verbatim).
    pub block_detail: Value,
    /// Newest `unlandable_cycle` counter.
    pub unlandable_cycles: Option<u64>,
    /// Dep-graph cycle detected for this PR's component.
    pub cycle_detected: bool,
    /// Members in that cycle.
    pub cycle_member_count: usize,
    /// The runner reached coord's verdict.
    pub coord_reachable: bool,
    /// Coord's leader lease was fresh.
    pub leader_healthy: bool,
}

/// The stable plan filename for a `(date, class, pr)` — the naming the plans-dir
/// dedup scan keys on (`coord-<class>-`).
pub fn plan_filename(date: &str, defect_class: &str, pr: u64) -> String {
    format!("{date}-coord-{defect_class}-{pr}.md")
}

/// Render a coord-defect remediation plan (Markdown). PURE — no IO, no clock.
pub fn render_remediation_plan(ctx: &RemediationPlanContext) -> String {
    let detail_pretty =
        serde_json::to_string_pretty(&ctx.block_detail).unwrap_or_else(|_| "null".to_string());
    let outer = ctx.outer_state.as_deref().unwrap_or("(unknown)");
    let block = ctx.block_reason.as_deref().unwrap_or("(none)");
    let cycles = ctx
        .unlandable_cycles
        .map(|c| c.to_string())
        .unwrap_or_else(|| "n/a".to_string());
    let green_mins = ctx.green_for_secs / 60;

    format!(
        "# Coord defect remediation — {class} on {repo}#{pr}\n\
\n\
> **Status: DRAFT {date}.** Auto-generated by the runner PR shepherd\n\
> (device-local, coord-independent watchdog — plan\n\
> `2026-07-04-runner-pr-shepherd.md`). The runner NEVER admin-merges; this\n\
> plan is the last-resort output when coord itself is the wedged/unreachable\n\
> component. Vet before implementing (`/vet-imp`).\n\
\n\
**Date: {date}**\n\
**Repo: {repo}** &nbsp; **PR: #{pr}** &nbsp; **Head: `{head}`**\n\
**Defect class: `{class}`**\n\
\n\
## Symptom\n\
\n\
{repo}#{pr} has been fully green (all non-skipped checks passing) on an\n\
unchanged head for **{green_mins} min** yet is still open — the device-local\n\
shepherd's independent GitHub witness. Coord's merge train is not landing it,\n\
and the disposition classifies as a coord defect rather than a legitimate\n\
hold or transient state.\n\
\n\
- Coord reachable: **{coord_reachable}**\n\
- Coord leader healthy: **{leader_healthy}**\n\
- Verdict outer_state: **{outer}**\n\
- Verdict block_reason: **{block}**\n\
- Unlandable cycles: **{cycles}**\n\
- Dep-graph cycle detected: **{cycle_detected}** ({members} member(s))\n\
\n\
### Coord's stated next action\n\
\n\
> {next_action}\n\
\n\
## Verbatim evidence\n\
\n\
Newest `predicate_eval.detail` from `GET /pr-merge/events/{repo}/{pr}`:\n\
\n\
```json\n\
{detail}\n\
```\n\
\n\
## Suspected coord code path\n\
\n\
`{suspected}`\n\
\n\
This class (`{class}`) points at the above as the first place to look. Confirm\n\
against coord main before changing anything — the mapping is a hint, not a\n\
diagnosis.\n\
\n\
## Detection-gap note\n\
\n\
Coord's own detectors (`stuck_pr_watcher.rs` detector 4\n\
`pr_merge_green_unlanded`, the Tier-2 `pr_merge_unlandable_escalated` alert,\n\
`stuck_pr_reconciler.rs`) run INSIDE coord's leader loop. If this PR reached a\n\
device-local last-resort remediation, either those detectors did not fire or\n\
coord could not act on them. Consider: should a coord-external signal have\n\
caught this sooner, and is the `{class}` classification threshold correct?\n\
\n\
## Remediation task\n\
\n\
1. Reproduce the classification from the evidence above.\n\
2. Locate the defect in `{suspected}` (verify against current coord main).\n\
3. Propose the minimal fix + a regression test.\n\
4. Land through coord's normal merge train (do NOT hand-merge).\n\
",
        class = ctx.defect_class,
        repo = ctx.repo_full_name,
        pr = ctx.pr_number,
        head = ctx.head_sha,
        date = ctx.date,
        green_mins = green_mins,
        coord_reachable = ctx.coord_reachable,
        leader_healthy = ctx.leader_healthy,
        outer = outer,
        block = block,
        cycles = cycles,
        cycle_detected = ctx.cycle_detected,
        members = ctx.cycle_member_count,
        next_action = if ctx.next_action.trim().is_empty() {
            "(none reported)"
        } else {
            ctx.next_action.trim()
        },
        detail = detail_pretty,
        suspected = ctx.suspected_coord_path,
    )
}

/// Does a plan file's content read as OPEN (not terminated)? A plan carrying a
/// terminal `Status:` marker (DONE / LANDED / CLOSED / MERGED / SHIPPED /
/// COMPLETE / ABANDONED) is CLOSED; anything else (incl. DRAFT / IN PROGRESS /
/// no status) is open. Only the head of the file is inspected by the caller.
pub fn plan_is_open(content: &str) -> bool {
    let lower = content.to_ascii_lowercase();
    // Look for a `status:` line with a terminal word near it.
    for line in lower.lines() {
        if line.contains("status:") {
            for term in [
                "done",
                "landed",
                "closed",
                "merged",
                "shipped",
                "complete",
                "abandoned",
                "retired",
            ] {
                if line.contains(term) {
                    return false;
                }
            }
        }
    }
    true
}

/// Pure Phase-4 dead-author decision: should a failed device-local notify route
/// to the `orphaned-red` bounded-fix spawn? True ONLY when coord cannot own the
/// nudge (`coord_down`), the authoring session is not live on this device
/// (`!author_live`), AND the task is terminal (`task_terminal`). All three must
/// hold — a live author or a running task means someone still owns the PR, and
/// a reachable coord means coord's own liveness branches cover it.
pub fn should_route_orphaned_red(coord_down: bool, author_live: bool, task_terminal: bool) -> bool {
    coord_down && !author_live && task_terminal
}

/// The plans directory. Overridable by `QONTINUI_PR_SHEPHERD_PLANS_DIR` (tests
/// point it at a temp dir); defaults to the canonical [`PLANS_DIR`].
pub fn plans_dir() -> PathBuf {
    std::env::var("QONTINUI_PR_SHEPHERD_PLANS_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(PLANS_DIR))
}

/// Scan `dir` for an OPEN plan whose filename marks it as a coord remediation
/// for `defect_class` (filename contains `coord-<class>-` and ends `.md`).
/// Reads only the head of each candidate (terminal status lives up top). Any IO
/// error is treated as "no open plan" (fail toward acting — the marker cooldown
/// still backstops double-spawns). This is the steward-coexistence dedup: the
/// merge-train-steward authors into the same dir with the same convention.
pub fn open_plan_exists(dir: &Path, defect_class: &str) -> bool {
    let needle = format!("coord-{defect_class}-");
    let Ok(entries) = std::fs::read_dir(dir) else {
        return false;
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if !name.ends_with(".md") || !name.contains(&needle) {
            continue;
        }
        // Read only the first ~4KB — the status marker is near the top.
        let content = match std::fs::read_to_string(entry.path()) {
            Ok(c) => c,
            Err(_) => continue,
        };
        let head: String = content.chars().take(4096).collect();
        if plan_is_open(&head) {
            return true;
        }
    }
    false
}

/// The disposition of a Phase 5 escalation attempt — for logging + tests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RemediationOutcome {
    /// Skipped: an open plan for this class already exists (steward/self dedup).
    SkippedOpenPlan,
    /// Skipped: a marker row is younger than the cooldown.
    SkippedCooldown,
    /// Plan + marker written; no session spawned (spawn disabled).
    PlannedNoSpawn { plan_path: String },
    /// Plan + marker written and a session spawned.
    Spawned {
        plan_path: String,
        session_id: String,
    },
    /// A DB / IO failure aborted the escalation (logged; retried next poll).
    Failed { reason: String },
}

/// Write the remediation plan file. Returns the absolute path written.
fn write_plan(dir: &Path, filename: &str, body: &str) -> Result<String, String> {
    std::fs::create_dir_all(dir).map_err(|e| format!("create plans dir: {e}"))?;
    let path = dir.join(filename);
    std::fs::write(&path, body).map_err(|e| format!("write plan {filename}: {e}"))?;
    Ok(path.to_string_lossy().to_string())
}

/// Create a standalone child `TaskRun` for the remediation prompt and (when
/// execution deps are available) fire it as a single-iteration agentic run.
/// Returns the new task run id. `blocks_parent: false` — the shepherd's spawn
/// never blocks anything.
async fn spawn_remediation_session(
    pg: &PgDb,
    deps: Option<&PrWatcherDeps>,
    task_name: &str,
    prompt: &str,
    model: Option<String>,
) -> Result<String, String> {
    use crate::database::CreateTaskRunInput;

    let id = format!(
        "pr-shepherd-remediation-{}",
        uuid::Uuid::new_v4().to_string().chars().take(12).collect::<String>()
    );
    let input = CreateTaskRunInput::new(&id, task_name)
        .with_prompt(prompt)
        .with_task_type("task")
        .with_workflow_type("unified")
        .with_workflow_name(task_name)
        .with_max_sessions(1)
        .with_blocks_parent(false);

    pg.create_task_run(&input)
        .await
        .map_err(|e| format!("create remediation task run: {e}"))?;

    match deps {
        Some(d) => {
            use crate::unified_workflow_executor::review_subtask::{execute_prompt_subtask, ReviewDeps};
            let review_deps = ReviewDeps {
                app_state: d.app_state.clone(),
                config_storage: d.config_storage.clone(),
                app_handle: d.app_handle.clone(),
                pid_tracker: d.pid_tracker.clone(),
            };
            execute_prompt_subtask(
                review_deps,
                id.clone(),
                task_name.to_string(),
                prompt.to_string(),
                model,
            );
        }
        None => {
            tracing::warn!(
                target: "pr_shepherd",
                task_run_id = %id,
                "pr_shepherd: remediation task row created but NOT executed (no execution deps in watcher)"
            );
        }
    }
    Ok(id)
}

/// Phase 5 entrypoint for a CONFIRMED coord defect: dedup, write the plan +
/// marker, and (when spawn is enabled) spawn the `/vet-imp <plan>` session.
///
/// The plans-dir / cooldown dedup runs here; the coord-live-attempt coexistence
/// check (rung i) runs at the call site before this is invoked.
pub async fn escalate_coord_defect(
    pg: &PgDb,
    deps: Option<&PrWatcherDeps>,
    ctx: &RemediationPlanContext,
) -> RemediationOutcome {
    let class = ctx.defect_class.as_str();
    let dir = plans_dir();

    // Dedup (ii): open plan for this class already exists (self OR steward).
    if open_plan_exists(&dir, class) {
        tracing::info!(
            target: "pr_shepherd",
            defect_class = class,
            pr_number = ctx.pr_number,
            "pr_shepherd: open remediation plan already exists for defect class — skipping (steward/self dedup)"
        );
        return RemediationOutcome::SkippedOpenPlan;
    }

    // Dedup (cooldown): a recent marker row for this class.
    let cooldown = super::pr_shepherd::remediation_cooldown();
    match pg
        .recent_pr_shepherd_remediation(class, cooldown.as_secs() as i64)
        .await
    {
        Ok(true) => {
            tracing::info!(
                target: "pr_shepherd",
                defect_class = class,
                pr_number = ctx.pr_number,
                cooldown_secs = cooldown.as_secs(),
                "pr_shepherd: recent remediation marker within cooldown — skipping"
            );
            return RemediationOutcome::SkippedCooldown;
        }
        Ok(false) => {}
        Err(e) => {
            // A marker read failure must not silently double-spawn; abort this
            // poll's escalation and retry next poll.
            return RemediationOutcome::Failed {
                reason: format!("marker cooldown check failed: {e}"),
            };
        }
    }

    // Write the plan.
    let filename = plan_filename(&ctx.date, class, ctx.pr_number);
    let body = render_remediation_plan(ctx);
    let plan_path = match write_plan(&dir, &filename, &body) {
        Ok(p) => p,
        Err(e) => return RemediationOutcome::Failed { reason: e },
    };

    finalize_remediation(
        pg,
        deps,
        class,
        &ctx.repo_full_name,
        ctx.pr_number,
        &plan_path,
        &format!("/vet-imp {plan_path}"),
        &format!("PR shepherd remediation: {class} on {}#{}", ctx.repo_full_name, ctx.pr_number),
    )
    .await
}

/// Phase 4 dead-author fallback: `orphaned-red` — the PR is GREEN but unmerged,
/// coord (the merge authority) is unreachable/leaderless so it can't own the
/// nudge, the authoring session is gone, and the task is terminal. Spawn a
/// BOUNDED DIAGNOSIS/SHEPHERD session (not vet-imp) with an inline prompt; no
/// coord-defect plan file.
///
/// The only call path (`pr_watcher`'s `GreenButUnmerged` →
/// `CoordDownLocalAlert` handler) is reachable exclusively when the runner's
/// own GitHub witness saw the PR fully green — the prompt must NOT claim
/// failing CI or instruct a "fix" (a fix commit would reset the green streak
/// and head for nothing).
///
/// Dedup is per `(class, repo, pr)` — unlike coord-defect classes (where one
/// coord fix covers every PR), an orphaned PR is per-PR work, so a class-only
/// key would silently drop a second orphaned PR inside the cooldown.
pub async fn escalate_orphaned_red(
    pg: &PgDb,
    deps: Option<&PrWatcherDeps>,
    repo_full_name: &str,
    pr_number: u64,
) -> RemediationOutcome {
    let class = "orphaned-red";

    let cooldown = super::pr_shepherd::remediation_cooldown();
    match pg
        .recent_pr_shepherd_remediation_for_pr(
            class,
            repo_full_name,
            pr_number,
            cooldown.as_secs() as i64,
        )
        .await
    {
        Ok(true) => {
            tracing::info!(
                target: "pr_shepherd",
                repo = %repo_full_name,
                pr_number = pr_number,
                "pr_shepherd: recent orphaned-red remediation for this PR within cooldown — skipping"
            );
            return RemediationOutcome::SkippedCooldown;
        }
        Ok(false) => {}
        Err(e) => {
            return RemediationOutcome::Failed {
                reason: format!("orphaned-red marker check failed: {e}"),
            };
        }
    }

    let prompt = orphaned_green_pr_prompt(repo_full_name, pr_number);
    finalize_remediation(
        pg,
        deps,
        class,
        repo_full_name,
        pr_number,
        "",
        &prompt,
        &format!("PR shepherd orphaned-red triage: {repo_full_name}#{pr_number}"),
    )
    .await
}

/// The bounded prompt for the orphaned GREEN-but-unmerged PR spawn. PURE —
/// unit-tested to stay truthful to the only reachable reality (PR fully green,
/// coord down, author gone): it must never claim failing CI, never instruct a
/// fix/push (a "fix" commit would reset the green streak and head for
/// nothing), and never permit an admin-merge.
pub fn orphaned_green_pr_prompt(repo_full_name: &str, pr_number: u64) -> String {
    format!(
        "The pull request {repo}#{pr} is fully GREEN (all non-skipped checks passing) but has \
         not been merged, coord — the fleet's sole merge authority — is unreachable or \
         leaderless, and the authoring session has ended, so no one owns landing it. \
         Diagnose why the PR is not landing and shepherd it per fleet policy, bounded: \
         verify with `gh` that CI really is green on the current head and the PR is still \
         open; check for blocking labels (`coord:blocked`, `coord:experimental`), unresolved \
         review threads, and branch-protection requirements; check coord's health and recent \
         merge activity. Do NOT push commits to the PR branch (CI is green — a 'fix' commit \
         would only reset the green streak), do NOT `gh pr merge`, and do NOT admin-merge — \
         coord's PR Merge Orchestrator is the sole landing authority. If the blocker is \
         something you can resolve per policy (e.g. a stale label the operator asked to \
         clear), resolve it; otherwise write a short report of findings (why the PR is \
         unlanded, coord's status, the recommended operator action) and stop.",
        repo = repo_full_name,
        pr = pr_number,
    )
}

/// Shared tail: insert the marker, then spawn iff `QONTINUI_PR_SHEPHERD_SPAWN`
/// is on, recording the spawned session id on the marker.
#[allow(clippy::too_many_arguments)]
async fn finalize_remediation(
    pg: &PgDb,
    deps: Option<&PrWatcherDeps>,
    class: &str,
    repo_full_name: &str,
    pr_number: u64,
    plan_path: &str,
    prompt: &str,
    task_name: &str,
) -> RemediationOutcome {
    // Insert the marker BEFORE spawning so a spawn failure still records that we
    // acted (the cooldown then debounces retries).
    let marker_id = match pg
        .insert_pr_shepherd_remediation(class, repo_full_name, pr_number, plan_path, None)
        .await
    {
        Ok(id) => id,
        Err(e) => {
            return RemediationOutcome::Failed {
                reason: format!("insert marker: {e}"),
            }
        }
    };

    if !super::pr_shepherd::spawn_enabled() {
        tracing::info!(
            target: "pr_shepherd",
            defect_class = class,
            pr_number = pr_number,
            plan_path = plan_path,
            "pr_shepherd: remediation plan + marker written; spawn DISABLED (QONTINUI_PR_SHEPHERD_SPAWN off) — no session"
        );
        return RemediationOutcome::PlannedNoSpawn {
            plan_path: plan_path.to_string(),
        };
    }

    let model = super::pr_shepherd::vetimp_model();
    match spawn_remediation_session(pg, deps, task_name, prompt, model).await {
        Ok(session_id) => {
            if let Err(e) = pg
                .set_pr_shepherd_remediation_session(&marker_id, &session_id)
                .await
            {
                tracing::warn!(
                    target: "pr_shepherd",
                    "pr_shepherd: spawned remediation {session_id} but failed to record it on marker {marker_id}: {e}"
                );
            }
            tracing::info!(
                target: "pr_shepherd",
                defect_class = class,
                pr_number = pr_number,
                plan_path = plan_path,
                session_id = %session_id,
                "pr_shepherd: spawned remediation session (last-resort rung)"
            );
            RemediationOutcome::Spawned {
                plan_path: plan_path.to_string(),
                session_id,
            }
        }
        Err(e) => RemediationOutcome::Failed {
            reason: format!("spawn: {e}"),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn ctx() -> RemediationPlanContext {
        RemediationPlanContext {
            date: "2026-07-07".to_string(),
            defect_class: "stale-ingest".to_string(),
            suspected_coord_path: "stuck_pr_reconciler.rs hydration".to_string(),
            repo_full_name: "qontinui/qontinui-web".to_string(),
            pr_number: 708,
            head_sha: "abc1234".to_string(),
            green_for_secs: 2 * 3600,
            outer_state: Some("BLOCKED".to_string()),
            block_reason: Some("behind-main-or-unstable".to_string()),
            next_action: "PR is BLOCKED on `behind-main-or-unstable`.".to_string(),
            block_detail: json!({ "coord_head": "OLDHEAD", "real_head": "abc1234" }),
            unlandable_cycles: Some(3),
            cycle_detected: false,
            cycle_member_count: 0,
            coord_reachable: true,
            leader_healthy: true,
        }
    }

    #[test]
    fn orphaned_red_route_requires_all_three_conditions() {
        // The only route-in case: coord down, author gone, task terminal.
        assert!(should_route_orphaned_red(true, false, true));
        // Any single condition off → no route.
        assert!(!should_route_orphaned_red(false, false, true), "coord up → coord owns it");
        assert!(!should_route_orphaned_red(true, true, true), "author live → owns it");
        assert!(!should_route_orphaned_red(true, false, false), "task running → owns it");
    }

    #[test]
    fn orphaned_prompt_matches_the_green_but_unmerged_reality() {
        // The only call path is the GreenButUnmerged → CoordDown → dead-author
        // route: the PR is GREEN. The prompt must never assert failing CI or
        // instruct a CI fix (which would push a pointless commit and reset the
        // streak), and must uphold the no-admin-merge fleet policy.
        let p = orphaned_green_pr_prompt("qontinui/qontinui-runner", 708);
        assert!(p.contains("qontinui/qontinui-runner#708"));
        assert!(p.contains("fully GREEN"), "must state the green witness");
        assert!(
            p.contains("coord — the fleet's sole merge authority — is unreachable"),
            "must state the coord-down context"
        );
        assert!(p.contains("authoring session has ended"), "author gone");
        let lower = p.to_ascii_lowercase();
        assert!(
            !lower.contains("failing ci") && !lower.contains("has failing"),
            "must NOT claim failing CI: the PR is green"
        );
        assert!(
            !lower.contains("fix the ci"),
            "must NOT instruct a CI fix on a green PR"
        );
        assert!(p.contains("do NOT admin-merge"), "no admin-merge, per policy");
        assert!(
            p.contains("Do NOT push commits"),
            "no pushes — a 'fix' commit would reset the green streak"
        );
    }

    #[test]
    fn plan_filename_is_stable() {
        assert_eq!(
            plan_filename("2026-07-07", "stale-ingest", 708),
            "2026-07-07-coord-stale-ingest-708.md"
        );
    }

    #[test]
    fn render_includes_evidence_and_class_and_path() {
        let md = render_remediation_plan(&ctx());
        assert!(md.contains("stale-ingest"), "defect class present");
        assert!(md.contains("qontinui/qontinui-web#708"), "repo#pr present");
        assert!(md.contains("abc1234"), "head present");
        assert!(md.contains("stuck_pr_reconciler.rs hydration"), "suspected path present");
        // Verbatim evidence rendered as pretty JSON.
        assert!(md.contains("\"coord_head\": \"OLDHEAD\""), "verbatim evidence present");
        assert!(md.contains("behind-main-or-unstable"), "block reason present");
        assert!(md.contains("Detection-gap note"), "detection-gap section present");
        assert!(md.contains("Status: DRAFT"), "draft status marker present");
    }

    #[test]
    fn plan_is_open_detects_terminal_status() {
        assert!(plan_is_open("# Foo\n> Status: DRAFT 2026-07-07\n"));
        assert!(plan_is_open("no status line at all"));
        assert!(!plan_is_open("> **Status: DONE 2026-07-01.**"));
        assert!(!plan_is_open("Status: LANDED"));
        assert!(!plan_is_open("status: merged via coord"));
        assert!(!plan_is_open("> Status: SHIPPED"));
    }

    #[test]
    fn open_plan_exists_matches_class_and_openness() {
        let dir = std::env::temp_dir().join(format!(
            "prshep-plans-{}",
            uuid::Uuid::new_v4().to_string().chars().take(8).collect::<String>()
        ));
        std::fs::create_dir_all(&dir).unwrap();

        // No plan yet.
        assert!(!open_plan_exists(&dir, "stale-ingest"));

        // An OPEN plan for the class → hit.
        std::fs::write(
            dir.join("2026-07-07-coord-stale-ingest-708.md"),
            "# x\n> Status: DRAFT\n",
        )
        .unwrap();
        assert!(open_plan_exists(&dir, "stale-ingest"));
        // A different class is unaffected.
        assert!(!open_plan_exists(&dir, "phantom-context-hang"));

        // A CLOSED plan for another class → not a hit.
        std::fs::write(
            dir.join("2026-07-01-coord-pass-but-no-land-500.md"),
            "# y\n> **Status: LANDED.**\n",
        )
        .unwrap();
        assert!(!open_plan_exists(&dir, "pass-but-no-land"));

        let _ = std::fs::remove_dir_all(&dir);
    }
}
