//! Deterministic `IrState` -> instrumented Expo screen (`.tsx`) renderer.
//!
//! Phase 1 (plan §4): pure-deterministic, no LLM. The emitted screen wraps the
//! `qontinui-mobile` instrumentation conventions (`useUIElement` /
//! `useUIElementWithProps` from `@qontinui/ui-bridge-native`) around one element per
//! state assertion. The presentational fill (layout/styling to the design tokens) is
//! Phase 2 (LLM via `run_claude_cli`) and is deliberately out of scope here — the
//! instrumentation must stay byte-deterministic so the snapshot can never silently
//! drift from what the matcher checks.

use qontinui_types::ir::IrState;

use crate::criteria::ParsedCriteria;
use crate::instrument::InstrumentedElement;

/// The output of inverting one [`IrState`]: the emitted screen source plus the
/// structured list of instrumented elements (the deterministic IR->element mapping the
/// golden test verifies against the real matcher).
#[derive(Debug, Clone)]
pub struct ScreenArtifact {
    /// State id this screen was inverted from.
    pub state_id: String,
    /// Expo Router screen path the generator would write this to
    /// (`app/<id>.tsx`, default-export fn component).
    pub file_path: String,
    /// The emitted `.tsx` source.
    pub tsx: String,
    /// One instrumented element per inverted assertion, in assertion order.
    pub elements: Vec<InstrumentedElement>,
}

/// Invert one `IrState` into an instrumented Expo screen.
///
/// Each `state.assertions[i]` becomes one instrumented element registered with the
/// UI Bridge native SDK. Assertions whose criteria are empty (no element signal) are
/// skipped for instrumentation — they would be vacuously matched and instrument nothing
/// observable.
pub fn generate_screen(state: &IrState) -> ScreenArtifact {
    let elements: Vec<InstrumentedElement> = state
        .assertions
        .iter()
        .map(|a| {
            let crit = ParsedCriteria::from_value(&a.target.criteria);
            (a.id.as_str(), crit)
        })
        .filter(|(_, crit)| !crit.is_empty())
        .map(|(id, crit)| InstrumentedElement::from_criteria(id, &crit))
        .collect();

    let tsx = render_tsx(state, &elements);
    ScreenArtifact {
        state_id: state.id.clone(),
        file_path: format!("app/{}.tsx", state.id),
        tsx,
        elements,
    }
}

/// Render the full `.tsx` source for the screen.
fn render_tsx(state: &IrState, elements: &[InstrumentedElement]) -> String {
    let component_name = pascal_case(&state.id);
    let needs_state_hook = elements.iter().any(|e| e.needs_press);

    let mut s = String::new();
    s.push_str("// AUTO-GENERATED by qontinui-app-generator (IR inversion, Phase 1).\n");
    s.push_str(&format!(
        "// Source IrState: {} ({})\n",
        state.id, state.name
    ));
    s.push_str("// Instrumentation is deterministic; do not hand-edit the bridge hooks.\n\n");

    // Imports. `useUIElementWithProps` is only imported when a press-needing element
    // is present (button/pressable), keeping the import set minimal + lint-clean.
    s.push_str("import { View, Text, Pressable } from 'react-native';\n");
    if needs_state_hook {
        s.push_str(
            "import { useUIElement, useUIElementWithProps } from '@qontinui/ui-bridge-native';\n",
        );
    } else {
        s.push_str("import { useUIElement } from '@qontinui/ui-bridge-native';\n");
    }
    s.push('\n');

    s.push_str(&format!(
        "export default function {component_name}Screen() {{\n"
    ));

    // Hook call sites — one per instrumented element.
    for (i, el) in elements.iter().enumerate() {
        render_hook(&mut s, i, el);
    }

    // Render tree.
    s.push_str("\n  return (\n");
    s.push_str("    <View>\n");
    for (i, el) in elements.iter().enumerate() {
        render_host_component(&mut s, i, el);
    }
    s.push_str("    </View>\n");
    s.push_str("  );\n");
    s.push_str("}\n");
    s
}

/// Emit the `useUIElement` / `useUIElementWithProps` hook call for one element.
fn render_hook(s: &mut String, i: usize, el: &InstrumentedElement) {
    let var = hook_var(i);
    let hook = if el.needs_press {
        "useUIElementWithProps"
    } else {
        "useUIElement"
    };
    if el.needs_press {
        s.push_str(&format!(
            "  const {{ ref: {var}Ref, onLayout: {var}Layout, bridgeProps: {var}Bridge, captureProps: {var}Capture }} = {hook}({{\n",
        ));
    } else {
        s.push_str(&format!(
            "  const {{ ref: {var}Ref, onLayout: {var}Layout, bridgeProps: {var}Bridge }} = {hook}({{\n",
        ));
    }
    s.push_str(&format!("    id: {},\n", ts_string(&el.element_id)));
    s.push_str(&format!("    type: {},\n", ts_string(&el.element_type)));
    if let Some(ref label) = el.label {
        s.push_str(&format!("    label: {},\n", ts_string(label)));
    }
    if let Some(ref role) = el.accessibility_role {
        s.push_str(&format!("    accessibilityRole: {},\n", ts_string(role)));
    }
    s.push_str("  });\n");
    if el.needs_press {
        // Wire a no-op press handler deterministically so the SDK's dead-button
        // backstop is satisfied and the element is press-capable. Phase 2 replaces the
        // body with the inverted IrTransition handler.
        s.push_str(&format!(
            "  {var}Capture({{ onPress: () => {{ /* transition handler wired in Phase 2 */ }} }});\n",
        ));
    }
}

/// Emit the host component (`<Pressable>` / `<View>`) for one element, spreading the
/// bridge props + `accessibilityRole`, with the visible `<Text>` child.
fn render_host_component(s: &mut String, i: usize, el: &InstrumentedElement) {
    let var = hook_var(i);
    let tag = if el.needs_press { "Pressable" } else { "View" };
    s.push_str(&format!("      <{tag}\n"));
    s.push_str(&format!("        ref={{{var}Ref}}\n"));
    s.push_str(&format!("        onLayout={{{var}Layout}}\n"));
    s.push_str(&format!("        {{...{var}Bridge}}\n"));
    if let Some(ref role) = el.accessibility_role {
        s.push_str(&format!("        accessibilityRole={}\n", ts_attr(role)));
    }
    if el.needs_press {
        s.push_str("        onPress={() => { /* transition handler wired in Phase 2 */ }}\n");
    }
    s.push_str("      >\n");
    if let Some(ref text) = el.visible_text {
        s.push_str(&format!("        <Text>{}</Text>\n", escape_jsx_text(text)));
    }
    s.push_str(&format!("      </{tag}>\n"));
}

/// Stable per-element hook variable name (`el0`, `el1`, …).
fn hook_var(i: usize) -> String {
    format!("el{i}")
}

/// Render a Rust string as a single-quoted TS string literal.
fn ts_string(s: &str) -> String {
    format!("'{}'", s.replace('\\', "\\\\").replace('\'', "\\'"))
}

/// Render a TS string as a JSX attribute value (`accessibilityRole="button"`).
fn ts_attr(s: &str) -> String {
    format!("\"{}\"", s.replace('"', "&quot;"))
}

/// Escape text for safe placement inside JSX (`{`/`}`/`<`/`>` are JSX-significant).
fn escape_jsx_text(s: &str) -> String {
    s.replace('{', "&#123;")
        .replace('}', "&#125;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// `pairing-confirm` -> `PairingConfirm`.
fn pascal_case(id: &str) -> String {
    let mut out = String::with_capacity(id.len());
    let mut upper_next = true;
    for ch in id.chars() {
        if ch.is_ascii_alphanumeric() {
            if upper_next {
                out.push(ch.to_ascii_uppercase());
                upper_next = false;
            } else {
                out.push(ch);
            }
        } else {
            upper_next = true;
        }
    }
    if out.is_empty() {
        "Screen".to_string()
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_case_handles_kebab() {
        assert_eq!(pascal_case("pairing-confirm"), "PairingConfirm");
        assert_eq!(pascal_case("pairing_error"), "PairingError");
    }

    #[test]
    fn ts_string_escapes_quotes() {
        assert_eq!(ts_string("it's"), "'it\\'s'");
    }

    #[test]
    fn escape_jsx_text_neutralizes_braces() {
        assert_eq!(escape_jsx_text("a{b}c"), "a&#123;b&#125;c");
    }
}
